// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package types

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncTimeRequest struct {
	SendTimeMs           int64    `protobuf:"varint,1,opt,name=sendTimeMs,proto3" json:"sendTimeMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncTimeRequest) Reset()         { *m = SyncTimeRequest{} }
func (m *SyncTimeRequest) String() string { return proto.CompactTextString(m) }
func (*SyncTimeRequest) ProtoMessage()    {}
func (*SyncTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *SyncTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTimeRequest.Unmarshal(m, b)
}
func (m *SyncTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTimeRequest.Marshal(b, m, deterministic)
}
func (m *SyncTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTimeRequest.Merge(m, src)
}
func (m *SyncTimeRequest) XXX_Size() int {
	return xxx_messageInfo_SyncTimeRequest.Size(m)
}
func (m *SyncTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTimeRequest proto.InternalMessageInfo

func (m *SyncTimeRequest) GetSendTimeMs() int64 {
	if m != nil {
		return m.SendTimeMs
	}
	return 0
}

type SyncTimeResponse struct {
	ClientTimestampMs    int64    `protobuf:"varint,1,opt,name=clientTimestampMs,proto3" json:"clientTimestampMs,omitempty"`
	ServerTimestampMs    int64    `protobuf:"varint,2,opt,name=serverTimestampMs,proto3" json:"serverTimestampMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncTimeResponse) Reset()         { *m = SyncTimeResponse{} }
func (m *SyncTimeResponse) String() string { return proto.CompactTextString(m) }
func (*SyncTimeResponse) ProtoMessage()    {}
func (*SyncTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *SyncTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTimeResponse.Unmarshal(m, b)
}
func (m *SyncTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTimeResponse.Marshal(b, m, deterministic)
}
func (m *SyncTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTimeResponse.Merge(m, src)
}
func (m *SyncTimeResponse) XXX_Size() int {
	return xxx_messageInfo_SyncTimeResponse.Size(m)
}
func (m *SyncTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTimeResponse proto.InternalMessageInfo

func (m *SyncTimeResponse) GetClientTimestampMs() int64 {
	if m != nil {
		return m.ClientTimestampMs
	}
	return 0
}

func (m *SyncTimeResponse) GetServerTimestampMs() int64 {
	if m != nil {
		return m.ServerTimestampMs
	}
	return 0
}

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ReCaptchaToken       string   `protobuf:"bytes,3,opt,name=reCaptchaToken,proto3" json:"reCaptchaToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetReCaptchaToken() string {
	if m != nil {
		return m.ReCaptchaToken
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChangePasswordRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UpdateDisplayNameRequest struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDisplayNameRequest) Reset()         { *m = UpdateDisplayNameRequest{} }
func (m *UpdateDisplayNameRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDisplayNameRequest) ProtoMessage()    {}
func (*UpdateDisplayNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *UpdateDisplayNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDisplayNameRequest.Unmarshal(m, b)
}
func (m *UpdateDisplayNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDisplayNameRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDisplayNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDisplayNameRequest.Merge(m, src)
}
func (m *UpdateDisplayNameRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDisplayNameRequest.Size(m)
}
func (m *UpdateDisplayNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDisplayNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDisplayNameRequest proto.InternalMessageInfo

func (m *UpdateDisplayNameRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type SessionToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionToken) Reset()         { *m = SessionToken{} }
func (m *SessionToken) String() string { return proto.CompactTextString(m) }
func (*SessionToken) ProtoMessage()    {}
func (*SessionToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *SessionToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionToken.Unmarshal(m, b)
}
func (m *SessionToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionToken.Marshal(b, m, deterministic)
}
func (m *SessionToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionToken.Merge(m, src)
}
func (m *SessionToken) XXX_Size() int {
	return xxx_messageInfo_SessionToken.Size(m)
}
func (m *SessionToken) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionToken.DiscardUnknown(m)
}

var xxx_messageInfo_SessionToken proto.InternalMessageInfo

func (m *SessionToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResendValidationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendValidationRequest) Reset()         { *m = ResendValidationRequest{} }
func (m *ResendValidationRequest) String() string { return proto.CompactTextString(m) }
func (*ResendValidationRequest) ProtoMessage()    {}
func (*ResendValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *ResendValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendValidationRequest.Unmarshal(m, b)
}
func (m *ResendValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendValidationRequest.Marshal(b, m, deterministic)
}
func (m *ResendValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendValidationRequest.Merge(m, src)
}
func (m *ResendValidationRequest) XXX_Size() int {
	return xxx_messageInfo_ResendValidationRequest.Size(m)
}
func (m *ResendValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendValidationRequest proto.InternalMessageInfo

func (m *ResendValidationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ValidateEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEmailRequest) Reset()         { *m = ValidateEmailRequest{} }
func (m *ValidateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailRequest) ProtoMessage()    {}
func (*ValidateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *ValidateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailRequest.Unmarshal(m, b)
}
func (m *ValidateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailRequest.Marshal(b, m, deterministic)
}
func (m *ValidateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailRequest.Merge(m, src)
}
func (m *ValidateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailRequest.Size(m)
}
func (m *ValidateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailRequest proto.InternalMessageInfo

func (m *ValidateEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ValidateEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SetupIntentRequest struct {
	ReCaptchaToken       string   `protobuf:"bytes,1,opt,name=reCaptchaToken,proto3" json:"reCaptchaToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupIntentRequest) Reset()         { *m = SetupIntentRequest{} }
func (m *SetupIntentRequest) String() string { return proto.CompactTextString(m) }
func (*SetupIntentRequest) ProtoMessage()    {}
func (*SetupIntentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *SetupIntentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupIntentRequest.Unmarshal(m, b)
}
func (m *SetupIntentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupIntentRequest.Marshal(b, m, deterministic)
}
func (m *SetupIntentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupIntentRequest.Merge(m, src)
}
func (m *SetupIntentRequest) XXX_Size() int {
	return xxx_messageInfo_SetupIntentRequest.Size(m)
}
func (m *SetupIntentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupIntentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupIntentRequest proto.InternalMessageInfo

func (m *SetupIntentRequest) GetReCaptchaToken() string {
	if m != nil {
		return m.ReCaptchaToken
	}
	return ""
}

type SetupIntentResponse struct {
	ClientSecret         string   `protobuf:"bytes,1,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupIntentResponse) Reset()         { *m = SetupIntentResponse{} }
func (m *SetupIntentResponse) String() string { return proto.CompactTextString(m) }
func (*SetupIntentResponse) ProtoMessage()    {}
func (*SetupIntentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *SetupIntentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupIntentResponse.Unmarshal(m, b)
}
func (m *SetupIntentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupIntentResponse.Marshal(b, m, deterministic)
}
func (m *SetupIntentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupIntentResponse.Merge(m, src)
}
func (m *SetupIntentResponse) XXX_Size() int {
	return xxx_messageInfo_SetupIntentResponse.Size(m)
}
func (m *SetupIntentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupIntentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetupIntentResponse proto.InternalMessageInfo

func (m *SetupIntentResponse) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type RefreshSessionRequest struct {
	ForceUpdateSubscriptionState bool     `protobuf:"varint,1,opt,name=forceUpdateSubscriptionState,proto3" json:"forceUpdateSubscriptionState,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *RefreshSessionRequest) Reset()         { *m = RefreshSessionRequest{} }
func (m *RefreshSessionRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshSessionRequest) ProtoMessage()    {}
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *RefreshSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshSessionRequest.Unmarshal(m, b)
}
func (m *RefreshSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshSessionRequest.Marshal(b, m, deterministic)
}
func (m *RefreshSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshSessionRequest.Merge(m, src)
}
func (m *RefreshSessionRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshSessionRequest.Size(m)
}
func (m *RefreshSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshSessionRequest proto.InternalMessageInfo

func (m *RefreshSessionRequest) GetForceUpdateSubscriptionState() bool {
	if m != nil {
		return m.ForceUpdateSubscriptionState
	}
	return false
}

type CreateStripeBillingSessionUrlRequest struct {
	ReturnUrl            string   `protobuf:"bytes,1,opt,name=returnUrl,proto3" json:"returnUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStripeBillingSessionUrlRequest) Reset()         { *m = CreateStripeBillingSessionUrlRequest{} }
func (m *CreateStripeBillingSessionUrlRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStripeBillingSessionUrlRequest) ProtoMessage()    {}
func (*CreateStripeBillingSessionUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{14}
}

func (m *CreateStripeBillingSessionUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStripeBillingSessionUrlRequest.Unmarshal(m, b)
}
func (m *CreateStripeBillingSessionUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStripeBillingSessionUrlRequest.Marshal(b, m, deterministic)
}
func (m *CreateStripeBillingSessionUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStripeBillingSessionUrlRequest.Merge(m, src)
}
func (m *CreateStripeBillingSessionUrlRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStripeBillingSessionUrlRequest.Size(m)
}
func (m *CreateStripeBillingSessionUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStripeBillingSessionUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStripeBillingSessionUrlRequest proto.InternalMessageInfo

func (m *CreateStripeBillingSessionUrlRequest) GetReturnUrl() string {
	if m != nil {
		return m.ReturnUrl
	}
	return ""
}

type CreateStripeBillingSessionUrlResponse struct {
	StripeBillingUrl     string   `protobuf:"bytes,1,opt,name=stripeBillingUrl,proto3" json:"stripeBillingUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStripeBillingSessionUrlResponse) Reset()         { *m = CreateStripeBillingSessionUrlResponse{} }
func (m *CreateStripeBillingSessionUrlResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStripeBillingSessionUrlResponse) ProtoMessage()    {}
func (*CreateStripeBillingSessionUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{15}
}

func (m *CreateStripeBillingSessionUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStripeBillingSessionUrlResponse.Unmarshal(m, b)
}
func (m *CreateStripeBillingSessionUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStripeBillingSessionUrlResponse.Marshal(b, m, deterministic)
}
func (m *CreateStripeBillingSessionUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStripeBillingSessionUrlResponse.Merge(m, src)
}
func (m *CreateStripeBillingSessionUrlResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStripeBillingSessionUrlResponse.Size(m)
}
func (m *CreateStripeBillingSessionUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStripeBillingSessionUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStripeBillingSessionUrlResponse proto.InternalMessageInfo

func (m *CreateStripeBillingSessionUrlResponse) GetStripeBillingUrl() string {
	if m != nil {
		return m.StripeBillingUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*SyncTimeRequest)(nil), "SyncTimeRequest")
	proto.RegisterType((*SyncTimeResponse)(nil), "SyncTimeResponse")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "ChangePasswordRequest")
	proto.RegisterType((*UpdateDisplayNameRequest)(nil), "UpdateDisplayNameRequest")
	proto.RegisterType((*SessionToken)(nil), "SessionToken")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "ForgotPasswordRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "ResetPasswordRequest")
	proto.RegisterType((*ResendValidationRequest)(nil), "ResendValidationRequest")
	proto.RegisterType((*ValidateEmailRequest)(nil), "ValidateEmailRequest")
	proto.RegisterType((*SetupIntentRequest)(nil), "SetupIntentRequest")
	proto.RegisterType((*SetupIntentResponse)(nil), "SetupIntentResponse")
	proto.RegisterType((*RefreshSessionRequest)(nil), "RefreshSessionRequest")
	proto.RegisterType((*CreateStripeBillingSessionUrlRequest)(nil), "CreateStripeBillingSessionUrlRequest")
	proto.RegisterType((*CreateStripeBillingSessionUrlResponse)(nil), "CreateStripeBillingSessionUrlResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 787 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdf, 0x6f, 0x1b, 0x45,
	0x10, 0x4e, 0x1a, 0x05, 0x92, 0x49, 0x9c, 0xda, 0x5b, 0x3b, 0x35, 0x47, 0x41, 0xd1, 0xaa, 0x0d,
	0x08, 0x35, 0x6b, 0x15, 0x84, 0x50, 0x45, 0x1f, 0x82, 0x9d, 0x52, 0x21, 0x1a, 0xa8, 0xee, 0x1a,
	0x1e, 0xe0, 0x01, 0xad, 0xef, 0x26, 0xe7, 0x55, 0xce, 0xbb, 0xc7, 0xee, 0x5e, 0x2b, 0xff, 0x6b,
	0xfc, 0x75, 0xe8, 0x7e, 0xe5, 0xee, 0x7c, 0xb6, 0x89, 0xf2, 0xe6, 0xfb, 0x76, 0x66, 0xbe, 0x99,
	0xdd, 0xf9, 0x3e, 0x19, 0x80, 0x27, 0x76, 0xc6, 0x62, 0xad, 0xac, 0x72, 0x3e, 0x0f, 0x95, 0x0a,
	0x23, 0x1c, 0x65, 0x5f, 0xd3, 0xe4, 0x7a, 0x84, 0xf3, 0xd8, 0x2e, 0x8a, 0xc3, 0xc7, 0x28, 0x2d,
	0xea, 0x58, 0x0b, 0x83, 0x7f, 0xcf, 0x55, 0x80, 0x91, 0xc9, 0x0f, 0xe8, 0x0b, 0x78, 0xe8, 0x2d,
	0xa4, 0xff, 0x5e, 0xcc, 0xd1, 0xc5, 0x7f, 0x12, 0x34, 0x96, 0x7c, 0x09, 0x60, 0x50, 0x06, 0x29,
	0x74, 0x69, 0x86, 0xdb, 0x27, 0xdb, 0x5f, 0xef, 0xb8, 0x35, 0x84, 0x4a, 0xe8, 0x56, 0x29, 0x26,
	0x56, 0xd2, 0x20, 0x79, 0x0e, 0x3d, 0x3f, 0x12, 0x28, 0x6d, 0x8a, 0x1a, 0xcb, 0xe7, 0xf1, 0x6d,
	0x6a, 0xfb, 0x20, 0x8d, 0x36, 0xa8, 0x3f, 0xa0, 0xae, 0x47, 0x3f, 0xc8, 0xa3, 0x5b, 0x07, 0xf4,
	0x06, 0x1e, 0xba, 0x18, 0x0a, 0x63, 0x51, 0x97, 0x2d, 0xf6, 0x61, 0x17, 0xe7, 0x5c, 0x44, 0x19,
	0xc5, 0xbe, 0x9b, 0x7f, 0x10, 0x07, 0xf6, 0x62, 0x6e, 0xcc, 0x47, 0xa5, 0x83, 0xac, 0xda, 0xbe,
	0x7b, 0xfb, 0x4d, 0x4e, 0xe1, 0x48, 0xe3, 0x84, 0xc7, 0xd6, 0x9f, 0xf1, 0xf7, 0xea, 0x06, 0xe5,
	0x70, 0x27, 0x8b, 0x58, 0x42, 0xe9, 0x39, 0x1c, 0xbe, 0x55, 0xa1, 0x90, 0xf7, 0x66, 0xa2, 0x57,
	0x30, 0x98, 0xcc, 0xb8, 0x0c, 0xf1, 0x5d, 0x81, 0x94, 0xa5, 0xea, 0x49, 0xdb, 0x4b, 0xed, 0x9d,
	0xc0, 0x81, 0xc4, 0x8f, 0xef, 0x9a, 0x35, 0xeb, 0x10, 0x7d, 0x05, 0xc3, 0xab, 0x38, 0xe0, 0x16,
	0x2f, 0x84, 0x89, 0x23, 0xbe, 0xf8, 0x8d, 0x57, 0x2f, 0x76, 0x02, 0x07, 0x41, 0x85, 0x16, 0xc5,
	0xeb, 0x10, 0x7d, 0x0a, 0x87, 0x1e, 0x1a, 0x23, 0x94, 0xcc, 0xc6, 0x4c, 0xc7, 0xb2, 0xd9, 0x2d,
	0x14, 0x63, 0x65, 0x1f, 0xf4, 0x0c, 0x06, 0x3f, 0x2b, 0x1d, 0x2a, 0xbb, 0xdc, 0xfa, 0xca, 0x5b,
	0xa0, 0x01, 0xf4, 0x5d, 0x34, 0x78, 0xb7, 0xe8, 0x8a, 0xf2, 0x41, 0x8d, 0x72, 0x79, 0xf0, 0x9d,
	0xf6, 0xe0, 0x23, 0x78, 0x9c, 0xb2, 0xc8, 0xe0, 0x0f, 0x1e, 0x89, 0x80, 0x5b, 0xa1, 0x36, 0x3f,
	0x0e, 0x1d, 0x43, 0xbf, 0x08, 0xc5, 0xd7, 0x29, 0x70, 0x8f, 0xb6, 0xe8, 0x2b, 0x20, 0x1e, 0xda,
	0x24, 0xfe, 0x45, 0x5a, 0x94, 0xb6, 0xac, 0xd0, 0x5e, 0xa2, 0xed, 0x95, 0x4b, 0xf4, 0x12, 0x1e,
	0x35, 0xb2, 0x0b, 0x91, 0x50, 0x38, 0xcc, 0xb5, 0xe0, 0xa1, 0xaf, 0xd1, 0x16, 0xc9, 0x0d, 0x8c,
	0xfe, 0x05, 0x03, 0x17, 0xaf, 0x35, 0x9a, 0x59, 0xf1, 0x5e, 0x25, 0xf7, 0x18, 0x9e, 0x5c, 0x2b,
	0xed, 0x63, 0xbe, 0x04, 0x5e, 0x32, 0x35, 0xbe, 0x16, 0x71, 0x7a, 0x1b, 0x9e, 0xe5, 0x36, 0x7f,
	0xf4, 0x3d, 0x77, 0x63, 0x0c, 0xbd, 0x80, 0xa7, 0x13, 0x8d, 0xe9, 0x91, 0xd5, 0x22, 0xc6, 0xb1,
	0x88, 0x22, 0x21, 0xc3, 0x82, 0xe8, 0x4a, 0xdf, 0xde, 0xd4, 0x13, 0xd8, 0xd7, 0x68, 0x13, 0x9d,
	0x62, 0x45, 0x97, 0x15, 0x40, 0x3d, 0x78, 0xf6, 0x3f, 0x55, 0x8a, 0x79, 0xbf, 0x81, 0xae, 0xa9,
	0x87, 0x54, 0xd5, 0x5a, 0xf8, 0xb7, 0xff, 0x7e, 0x0a, 0x07, 0x3f, 0x25, 0x76, 0xe6, 0xa1, 0xfe,
	0x20, 0x7c, 0x24, 0x2f, 0x60, 0xaf, 0x34, 0x19, 0xd2, 0x65, 0x4b, 0x16, 0xe5, 0xf4, 0xd8, 0xb2,
	0x03, 0xd1, 0x2d, 0x72, 0x06, 0x7b, 0xa5, 0x4f, 0x90, 0x2e, 0x5b, 0xb2, 0x0c, 0xa7, 0xc3, 0xea,
	0x02, 0xa0, 0x5b, 0xe4, 0x2b, 0xd8, 0xcd, 0x94, 0x4e, 0x3a, 0xac, 0xae, 0xf8, 0x76, 0xe0, 0x29,
	0xec, 0xbe, 0x41, 0x7b, 0x89, 0xe4, 0x98, 0xe5, 0x16, 0xcb, 0x4a, 0x8b, 0x65, 0xaf, 0x53, 0x8b,
	0x75, 0x76, 0xd8, 0x65, 0xca, 0xff, 0x23, 0x74, 0xdf, 0xa0, 0x9d, 0x70, 0x29, 0x17, 0x9e, 0xf7,
	0x7b, 0xae, 0xb3, 0x75, 0x29, 0x2d, 0x92, 0xef, 0xa1, 0xd7, 0x92, 0x37, 0xf9, 0x8c, 0xad, 0x93,
	0x7c, 0xc9, 0xf9, 0x12, 0x8e, 0x9a, 0x66, 0x43, 0x8e, 0xd9, 0x4a, 0xf7, 0x69, 0x33, 0x9e, 0x43,
	0xa7, 0x21, 0x13, 0x32, 0x60, 0xab, 0x64, 0xe3, 0xac, 0x19, 0x81, 0x6e, 0x91, 0x1f, 0xa0, 0xd3,
	0xd0, 0x3f, 0x19, 0xb0, 0x55, 0x7e, 0xd0, 0xa6, 0xfe, 0x35, 0x5d, 0xf2, 0x54, 0xd2, 0x19, 0x51,
	0xa5, 0x6b, 0x32, 0x64, 0x6b, 0xa4, 0xbe, 0xa1, 0x8b, 0x0b, 0x38, 0x6a, 0x9a, 0xd6, 0xbd, 0xaa,
	0x9c, 0x43, 0xaf, 0x58, 0xea, 0x4a, 0xb8, 0xe4, 0x11, 0x6b, 0x9b, 0x80, 0xd3, 0x67, 0x2b, 0xb4,
	0x4d, 0xb7, 0xc8, 0x5b, 0x18, 0x4e, 0xb8, 0xf4, 0x31, 0xca, 0x65, 0x51, 0x57, 0xdf, 0xda, 0x35,
	0x58, 0xdf, 0x4f, 0x0c, 0x5f, 0x6c, 0x14, 0x19, 0x79, 0xc6, 0xee, 0x22, 0x65, 0xe7, 0x94, 0xdd,
	0x49, 0xab, 0xf9, 0x2a, 0x35, 0x9d, 0x87, 0x1c, 0xb3, 0x95, 0x56, 0xd4, 0x7a, 0xcf, 0x31, 0xfb,
	0xf3, 0x79, 0x28, 0xec, 0x2c, 0x99, 0x32, 0x5f, 0xcd, 0x47, 0x37, 0x42, 0x5a, 0x35, 0x4b, 0xa6,
	0xf9, 0x8f, 0x33, 0x3f, 0x12, 0x23, 0x91, 0xfe, 0xfb, 0x90, 0x3c, 0x1a, 0xd9, 0x45, 0x8c, 0x66,
	0xfa, 0x49, 0x36, 0xee, 0x77, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xef, 0x74, 0xf1, 0x49, 0xbf,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	SyncTime(ctx context.Context, in *SyncTimeRequest, opts ...grpc.CallOption) (*SyncTimeResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*SessionToken, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*SessionToken, error)
	GetMe(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Me, error)
	GetCannySSOToken(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SessionToken, error)
	UpdateDisplayName(ctx context.Context, in *UpdateDisplayNameRequest, opts ...grpc.CallOption) (*Me, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*SessionToken, error)
	ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*SessionToken, error)
	ResendEmailValidation(ctx context.Context, in *ResendValidationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ForgotPassword(ctx context.Context, in *ResendValidationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateSetupIntent(ctx context.Context, in *SetupIntentRequest, opts ...grpc.CallOption) (*SetupIntentResponse, error)
	CancelStripeSubscription(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateStripeBillingSessionUrl(ctx context.Context, in *CreateStripeBillingSessionUrlRequest, opts ...grpc.CallOption) (*CreateStripeBillingSessionUrlResponse, error)
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*SessionToken, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SyncTime(ctx context.Context, in *SyncTimeRequest, opts ...grpc.CallOption) (*SyncTimeResponse, error) {
	out := new(SyncTimeResponse)
	err := c.cc.Invoke(ctx, "/AuthService/SyncTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/AuthService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetMe(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Me, error) {
	out := new(Me)
	err := c.cc.Invoke(ctx, "/AuthService/GetMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetCannySSOToken(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/AuthService/GetCannySSOToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateDisplayName(ctx context.Context, in *UpdateDisplayNameRequest, opts ...grpc.CallOption) (*Me, error) {
	out := new(Me)
	err := c.cc.Invoke(ctx, "/AuthService/UpdateDisplayName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/AuthService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/AuthService/ValidateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/AuthService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResendEmailValidation(ctx context.Context, in *ResendValidationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/AuthService/ResendEmailValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ForgotPassword(ctx context.Context, in *ResendValidationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/AuthService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateSetupIntent(ctx context.Context, in *SetupIntentRequest, opts ...grpc.CallOption) (*SetupIntentResponse, error) {
	out := new(SetupIntentResponse)
	err := c.cc.Invoke(ctx, "/AuthService/CreateSetupIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CancelStripeSubscription(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/AuthService/CancelStripeSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateStripeBillingSessionUrl(ctx context.Context, in *CreateStripeBillingSessionUrlRequest, opts ...grpc.CallOption) (*CreateStripeBillingSessionUrlResponse, error) {
	out := new(CreateStripeBillingSessionUrlResponse)
	err := c.cc.Invoke(ctx, "/AuthService/CreateStripeBillingSessionUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/AuthService/RefreshSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	SyncTime(context.Context, *SyncTimeRequest) (*SyncTimeResponse, error)
	Register(context.Context, *RegisterRequest) (*SessionToken, error)
	Login(context.Context, *LoginRequest) (*SessionToken, error)
	GetMe(context.Context, *empty.Empty) (*Me, error)
	GetCannySSOToken(context.Context, *empty.Empty) (*SessionToken, error)
	UpdateDisplayName(context.Context, *UpdateDisplayNameRequest) (*Me, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*SessionToken, error)
	ValidateEmail(context.Context, *ValidateEmailRequest) (*empty.Empty, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*SessionToken, error)
	ResendEmailValidation(context.Context, *ResendValidationRequest) (*empty.Empty, error)
	ForgotPassword(context.Context, *ResendValidationRequest) (*empty.Empty, error)
	CreateSetupIntent(context.Context, *SetupIntentRequest) (*SetupIntentResponse, error)
	CancelStripeSubscription(context.Context, *empty.Empty) (*empty.Empty, error)
	CreateStripeBillingSessionUrl(context.Context, *CreateStripeBillingSessionUrlRequest) (*CreateStripeBillingSessionUrlResponse, error)
	RefreshSession(context.Context, *RefreshSessionRequest) (*SessionToken, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) SyncTime(ctx context.Context, req *SyncTimeRequest) (*SyncTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncTime not implemented")
}
func (*UnimplementedAuthServiceServer) Register(ctx context.Context, req *RegisterRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) GetMe(ctx context.Context, req *empty.Empty) (*Me, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMe not implemented")
}
func (*UnimplementedAuthServiceServer) GetCannySSOToken(ctx context.Context, req *empty.Empty) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCannySSOToken not implemented")
}
func (*UnimplementedAuthServiceServer) UpdateDisplayName(ctx context.Context, req *UpdateDisplayNameRequest) (*Me, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDisplayName not implemented")
}
func (*UnimplementedAuthServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedAuthServiceServer) ValidateEmail(ctx context.Context, req *ValidateEmailRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateEmail not implemented")
}
func (*UnimplementedAuthServiceServer) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (*UnimplementedAuthServiceServer) ResendEmailValidation(ctx context.Context, req *ResendValidationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendEmailValidation not implemented")
}
func (*UnimplementedAuthServiceServer) ForgotPassword(ctx context.Context, req *ResendValidationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (*UnimplementedAuthServiceServer) CreateSetupIntent(ctx context.Context, req *SetupIntentRequest) (*SetupIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSetupIntent not implemented")
}
func (*UnimplementedAuthServiceServer) CancelStripeSubscription(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelStripeSubscription not implemented")
}
func (*UnimplementedAuthServiceServer) CreateStripeBillingSessionUrl(ctx context.Context, req *CreateStripeBillingSessionUrlRequest) (*CreateStripeBillingSessionUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStripeBillingSessionUrl not implemented")
}
func (*UnimplementedAuthServiceServer) RefreshSession(ctx context.Context, req *RefreshSessionRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSession not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_SyncTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SyncTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/SyncTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SyncTime(ctx, req.(*SyncTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetMe(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetCannySSOToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetCannySSOToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/GetCannySSOToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetCannySSOToken(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/UpdateDisplayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateDisplayName(ctx, req.(*UpdateDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/ValidateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateEmail(ctx, req.(*ValidateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResendEmailValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResendEmailValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/ResendEmailValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResendEmailValidation(ctx, req.(*ResendValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ForgotPassword(ctx, req.(*ResendValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateSetupIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateSetupIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/CreateSetupIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateSetupIntent(ctx, req.(*SetupIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CancelStripeSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CancelStripeSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/CancelStripeSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CancelStripeSubscription(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateStripeBillingSessionUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStripeBillingSessionUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateStripeBillingSessionUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/CreateStripeBillingSessionUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateStripeBillingSessionUrl(ctx, req.(*CreateStripeBillingSessionUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/RefreshSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncTime",
			Handler:    _AuthService_SyncTime_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _AuthService_GetMe_Handler,
		},
		{
			MethodName: "GetCannySSOToken",
			Handler:    _AuthService_GetCannySSOToken_Handler,
		},
		{
			MethodName: "UpdateDisplayName",
			Handler:    _AuthService_UpdateDisplayName_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AuthService_ChangePassword_Handler,
		},
		{
			MethodName: "ValidateEmail",
			Handler:    _AuthService_ValidateEmail_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AuthService_ResetPassword_Handler,
		},
		{
			MethodName: "ResendEmailValidation",
			Handler:    _AuthService_ResendEmailValidation_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AuthService_ForgotPassword_Handler,
		},
		{
			MethodName: "CreateSetupIntent",
			Handler:    _AuthService_CreateSetupIntent_Handler,
		},
		{
			MethodName: "CancelStripeSubscription",
			Handler:    _AuthService_CancelStripeSubscription_Handler,
		},
		{
			MethodName: "CreateStripeBillingSessionUrl",
			Handler:    _AuthService_CreateStripeBillingSessionUrl_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _AuthService_RefreshSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
