// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kkc_models.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block_Type int32

const (
	Block_NOT_SET     Block_Type = 0
	Block_BACKEND_API Block_Type = 1
	Block_STATIC_SITE Block_Type = 2
	Block_WEB_APP     Block_Type = 3
	Block_JAMSTACK    Block_Type = 4
	Block_JOB         Block_Type = 5
	Block_CRON_JOB    Block_Type = 6
	Block_WORKER      Block_Type = 7
	Block_CATALOG     Block_Type = 8
	Block_HELM        Block_Type = 9
)

var Block_Type_name = map[int32]string{
	0: "NOT_SET",
	1: "BACKEND_API",
	2: "STATIC_SITE",
	3: "WEB_APP",
	4: "JAMSTACK",
	5: "JOB",
	6: "CRON_JOB",
	7: "WORKER",
	8: "CATALOG",
	9: "HELM",
}

var Block_Type_value = map[string]int32{
	"NOT_SET":     0,
	"BACKEND_API": 1,
	"STATIC_SITE": 2,
	"WEB_APP":     3,
	"JAMSTACK":    4,
	"JOB":         5,
	"CRON_JOB":    6,
	"WORKER":      7,
	"CATALOG":     8,
	"HELM":        9,
}

func (x Block_Type) String() string {
	return proto.EnumName(Block_Type_name, int32(x))
}

func (Block_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{2, 0}
}

type Release_Type int32

const (
	Release_NOT_SET  Release_Type = 0
	Release_DEPLOY   Release_Type = 1
	Release_UNDEPLOY Release_Type = 2
	Release_SUSPEND  Release_Type = 3
	Release_ROLLBACK Release_Type = 4
)

var Release_Type_name = map[int32]string{
	0: "NOT_SET",
	1: "DEPLOY",
	2: "UNDEPLOY",
	3: "SUSPEND",
	4: "ROLLBACK",
}

var Release_Type_value = map[string]int32{
	"NOT_SET":  0,
	"DEPLOY":   1,
	"UNDEPLOY": 2,
	"SUSPEND":  3,
	"ROLLBACK": 4,
}

func (x Release_Type) String() string {
	return proto.EnumName(Release_Type_name, int32(x))
}

func (Release_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{3, 0}
}

type BuildConfig_Language int32

const (
	BuildConfig_NOT_SET    BuildConfig_Language = 0
	BuildConfig_DOCKERFILE BuildConfig_Language = 1
	BuildConfig_GOLANG     BuildConfig_Language = 2
	BuildConfig_NODEJS     BuildConfig_Language = 3
	BuildConfig_PYTHON     BuildConfig_Language = 4
	BuildConfig_JAVA       BuildConfig_Language = 5
	BuildConfig_RUBY       BuildConfig_Language = 6
	BuildConfig_PHP        BuildConfig_Language = 7
	BuildConfig_RUST       BuildConfig_Language = 8
	BuildConfig_ELIXIR     BuildConfig_Language = 9
)

var BuildConfig_Language_name = map[int32]string{
	0: "NOT_SET",
	1: "DOCKERFILE",
	2: "GOLANG",
	3: "NODEJS",
	4: "PYTHON",
	5: "JAVA",
	6: "RUBY",
	7: "PHP",
	8: "RUST",
	9: "ELIXIR",
}

var BuildConfig_Language_value = map[string]int32{
	"NOT_SET":    0,
	"DOCKERFILE": 1,
	"GOLANG":     2,
	"NODEJS":     3,
	"PYTHON":     4,
	"JAVA":       5,
	"RUBY":       6,
	"PHP":        7,
	"RUST":       8,
	"ELIXIR":     9,
}

func (x BuildConfig_Language) String() string {
	return proto.EnumName(BuildConfig_Language_name, int32(x))
}

func (BuildConfig_Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{4, 0}
}

type RunConfig_Protocol int32

const (
	RunConfig_NOT_SET RunConfig_Protocol = 0
	RunConfig_HTTP    RunConfig_Protocol = 1
	RunConfig_GRPC    RunConfig_Protocol = 2
)

var RunConfig_Protocol_name = map[int32]string{
	0: "NOT_SET",
	1: "HTTP",
	2: "GRPC",
}

var RunConfig_Protocol_value = map[string]int32{
	"NOT_SET": 0,
	"HTTP":    1,
	"GRPC":    2,
}

func (x RunConfig_Protocol) String() string {
	return proto.EnumName(RunConfig_Protocol_name, int32(x))
}

func (RunConfig_Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{5, 0}
}

type Status_State int32

const (
	Status_NOT_SET       Status_State = 0
	Status_FAIL          Status_State = 1
	Status_SUCCESS       Status_State = 2
	Status_RUNNING       Status_State = 3
	Status_PENDING       Status_State = 4
	Status_ABORTED       Status_State = 5
	Status_REVIEW_DEPLOY Status_State = 6
)

var Status_State_name = map[int32]string{
	0: "NOT_SET",
	1: "FAIL",
	2: "SUCCESS",
	3: "RUNNING",
	4: "PENDING",
	5: "ABORTED",
	6: "REVIEW_DEPLOY",
}

var Status_State_value = map[string]int32{
	"NOT_SET":       0,
	"FAIL":          1,
	"SUCCESS":       2,
	"RUNNING":       3,
	"PENDING":       4,
	"ABORTED":       5,
	"REVIEW_DEPLOY": 6,
}

func (x Status_State) String() string {
	return proto.EnumName(Status_State_name, int32(x))
}

func (Status_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{10, 0}
}

type BuildStatus_State int32

const (
	BuildStatus_NOT_SET        BuildStatus_State = 0
	BuildStatus_UNKNOWN        BuildStatus_State = 1
	BuildStatus_QUEUED         BuildStatus_State = 2
	BuildStatus_WORKING        BuildStatus_State = 3
	BuildStatus_SUCCESS        BuildStatus_State = 4
	BuildStatus_FAILURE        BuildStatus_State = 5
	BuildStatus_INTERNAL_ERROR BuildStatus_State = 6
	BuildStatus_TIMEOUT        BuildStatus_State = 7
	BuildStatus_CANCELLED      BuildStatus_State = 8
	BuildStatus_EXPIRED        BuildStatus_State = 9
)

var BuildStatus_State_name = map[int32]string{
	0: "NOT_SET",
	1: "UNKNOWN",
	2: "QUEUED",
	3: "WORKING",
	4: "SUCCESS",
	5: "FAILURE",
	6: "INTERNAL_ERROR",
	7: "TIMEOUT",
	8: "CANCELLED",
	9: "EXPIRED",
}

var BuildStatus_State_value = map[string]int32{
	"NOT_SET":        0,
	"UNKNOWN":        1,
	"QUEUED":         2,
	"WORKING":        3,
	"SUCCESS":        4,
	"FAILURE":        5,
	"INTERNAL_ERROR": 6,
	"TIMEOUT":        7,
	"CANCELLED":      8,
	"EXPIRED":        9,
}

func (x BuildStatus_State) String() string {
	return proto.EnumName(BuildStatus_State_name, int32(x))
}

func (BuildStatus_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{12, 0}
}

type BlockStatus_State int32

const (
	BlockStatus_NOT_SET   BlockStatus_State = 0
	BlockStatus_HEALTHY   BlockStatus_State = 1
	BlockStatus_UNHEALTHY BlockStatus_State = 2
	BlockStatus_SUSPENDED BlockStatus_State = 3
	BlockStatus_SLEEPING  BlockStatus_State = 4
)

var BlockStatus_State_name = map[int32]string{
	0: "NOT_SET",
	1: "HEALTHY",
	2: "UNHEALTHY",
	3: "SUSPENDED",
	4: "SLEEPING",
}

var BlockStatus_State_value = map[string]int32{
	"NOT_SET":   0,
	"HEALTHY":   1,
	"UNHEALTHY": 2,
	"SUSPENDED": 3,
	"SLEEPING":  4,
}

func (x BlockStatus_State) String() string {
	return proto.EnumName(BlockStatus_State_name, int32(x))
}

func (BlockStatus_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{14, 0}
}

type BlockInstance_State int32

const (
	BlockInstance_NOT_SET    BlockInstance_State = 0
	BlockInstance_RUNNING    BlockInstance_State = 1
	BlockInstance_COMPLETED  BlockInstance_State = 2
	BlockInstance_ERROR      BlockInstance_State = 3
	BlockInstance_OOM_KILLED BlockInstance_State = 4
)

var BlockInstance_State_name = map[int32]string{
	0: "NOT_SET",
	1: "RUNNING",
	2: "COMPLETED",
	3: "ERROR",
	4: "OOM_KILLED",
}

var BlockInstance_State_value = map[string]int32{
	"NOT_SET":    0,
	"RUNNING":    1,
	"COMPLETED":  2,
	"ERROR":      3,
	"OOM_KILLED": 4,
}

func (x BlockInstance_State) String() string {
	return proto.EnumName(BlockInstance_State_name, int32(x))
}

func (BlockInstance_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{17, 0}
}

type AccessPermission_Role int32

const (
	AccessPermission_NOT_SET       AccessPermission_Role = 0
	AccessPermission_PUBLIC        AccessPermission_Role = 1
	AccessPermission_AUTHENTICATED AccessPermission_Role = 2
	AccessPermission_VIEWER        AccessPermission_Role = 3
	AccessPermission_EDITOR        AccessPermission_Role = 4
	AccessPermission_ADMIN         AccessPermission_Role = 5
	AccessPermission_OWNER         AccessPermission_Role = 6
)

var AccessPermission_Role_name = map[int32]string{
	0: "NOT_SET",
	1: "PUBLIC",
	2: "AUTHENTICATED",
	3: "VIEWER",
	4: "EDITOR",
	5: "ADMIN",
	6: "OWNER",
}

var AccessPermission_Role_value = map[string]int32{
	"NOT_SET":       0,
	"PUBLIC":        1,
	"AUTHENTICATED": 2,
	"VIEWER":        3,
	"EDITOR":        4,
	"ADMIN":         5,
	"OWNER":         6,
}

func (x AccessPermission_Role) String() string {
	return proto.EnumName(AccessPermission_Role_name, int32(x))
}

func (AccessPermission_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{28, 0}
}

type JobStatus_State int32

const (
	JobStatus_NOT_SET    JobStatus_State = 0
	JobStatus_PENDING    JobStatus_State = 1
	JobStatus_RUNNING    JobStatus_State = 2
	JobStatus_COMPLETED  JobStatus_State = 3
	JobStatus_DELETED    JobStatus_State = 4
	JobStatus_ERROR      JobStatus_State = 5
	JobStatus_OOM_KILLED JobStatus_State = 6
)

var JobStatus_State_name = map[int32]string{
	0: "NOT_SET",
	1: "PENDING",
	2: "RUNNING",
	3: "COMPLETED",
	4: "DELETED",
	5: "ERROR",
	6: "OOM_KILLED",
}

var JobStatus_State_value = map[string]int32{
	"NOT_SET":    0,
	"PENDING":    1,
	"RUNNING":    2,
	"COMPLETED":  3,
	"DELETED":    4,
	"ERROR":      5,
	"OOM_KILLED": 6,
}

func (x JobStatus_State) String() string {
	return proto.EnumName(JobStatus_State_name, int32(x))
}

func (JobStatus_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{30, 0}
}

type Environment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{0}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Blocks struct {
	Items                []*Block `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blocks) Reset()         { *m = Blocks{} }
func (m *Blocks) String() string { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()    {}
func (*Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{1}
}

func (m *Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blocks.Unmarshal(m, b)
}
func (m *Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blocks.Marshal(b, m, deterministic)
}
func (m *Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blocks.Merge(m, src)
}
func (m *Blocks) XXX_Size() int {
	return xxx_messageInfo_Blocks.Size(m)
}
func (m *Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_Blocks proto.InternalMessageInfo

func (m *Blocks) GetItems() []*Block {
	if m != nil {
		return m.Items
	}
	return nil
}

type Block struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EnvId                string              `protobuf:"bytes,3,opt,name=envId,proto3" json:"envId,omitempty"`
	DisplayName          string              `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Releases             map[string]*Release `protobuf:"bytes,5,rep,name=releases,proto3" json:"releases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomDomains        []string            `protobuf:"bytes,6,rep,name=customDomains,proto3" json:"customDomains,omitempty"`
	IsPublicURL          bool                `protobuf:"varint,7,opt,name=isPublicURL,proto3" json:"isPublicURL,omitempty"`
	ParentBlockName      string              `protobuf:"bytes,8,opt,name=parentBlockName,proto3" json:"parentBlockName,omitempty"`
	ParentBlockEnvId     string              `protobuf:"bytes,9,opt,name=parentBlockEnvId,proto3" json:"parentBlockEnvId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Block) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Block) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *Block) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Block) GetReleases() map[string]*Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

func (m *Block) GetCustomDomains() []string {
	if m != nil {
		return m.CustomDomains
	}
	return nil
}

func (m *Block) GetIsPublicURL() bool {
	if m != nil {
		return m.IsPublicURL
	}
	return false
}

func (m *Block) GetParentBlockName() string {
	if m != nil {
		return m.ParentBlockName
	}
	return ""
}

func (m *Block) GetParentBlockEnvId() string {
	if m != nil {
		return m.ParentBlockEnvId
	}
	return ""
}

type Release struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	BuildConfig          *BuildConfig         `protobuf:"bytes,3,opt,name=buildConfig,proto3" json:"buildConfig,omitempty"`
	RunConfig            *RunConfig           `protobuf:"bytes,4,opt,name=runConfig,proto3" json:"runConfig,omitempty"`
	Status               *Status              `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	EndedAt              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=endedAt,proto3" json:"endedAt,omitempty"`
	Type                 Release_Type         `protobuf:"varint,8,opt,name=type,proto3,enum=Release_Type" json:"type,omitempty"`
	Tags                 []string             `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}
func (*Release) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{3}
}

func (m *Release) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Release.Unmarshal(m, b)
}
func (m *Release) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Release.Marshal(b, m, deterministic)
}
func (m *Release) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Release.Merge(m, src)
}
func (m *Release) XXX_Size() int {
	return xxx_messageInfo_Release.Size(m)
}
func (m *Release) XXX_DiscardUnknown() {
	xxx_messageInfo_Release.DiscardUnknown(m)
}

var xxx_messageInfo_Release proto.InternalMessageInfo

func (m *Release) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Release) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Release) GetBuildConfig() *BuildConfig {
	if m != nil {
		return m.BuildConfig
	}
	return nil
}

func (m *Release) GetRunConfig() *RunConfig {
	if m != nil {
		return m.RunConfig
	}
	return nil
}

func (m *Release) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Release) GetStartedAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *Release) GetEndedAt() *timestamp.Timestamp {
	if m != nil {
		return m.EndedAt
	}
	return nil
}

func (m *Release) GetType() Release_Type {
	if m != nil {
		return m.Type
	}
	return Release_NOT_SET
}

func (m *Release) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type BuildConfig struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string               `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Language             BuildConfig_Language `protobuf:"varint,3,opt,name=language,proto3,enum=BuildConfig_Language" json:"language,omitempty"`
	LanguageVersion      string               `protobuf:"bytes,4,opt,name=languageVersion,proto3" json:"languageVersion,omitempty"`
	BuildCommand         string               `protobuf:"bytes,5,opt,name=buildCommand,proto3" json:"buildCommand,omitempty"`
	RunCommand           string               `protobuf:"bytes,6,opt,name=runCommand,proto3" json:"runCommand,omitempty"`
	PathToCode           string               `protobuf:"bytes,7,opt,name=pathToCode,proto3" json:"pathToCode,omitempty"`
	PathToStaticOutput   string               `protobuf:"bytes,11,opt,name=pathToStaticOutput,proto3" json:"pathToStaticOutput,omitempty"`
	DockerfileFileName   string               `protobuf:"bytes,8,opt,name=dockerfileFileName,proto3" json:"dockerfileFileName,omitempty"`
	BuildArgs            map[string]string    `protobuf:"bytes,9,rep,name=buildArgs,proto3" json:"buildArgs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Repository           *Repository          `protobuf:"bytes,10,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuildConfig) Reset()         { *m = BuildConfig{} }
func (m *BuildConfig) String() string { return proto.CompactTextString(m) }
func (*BuildConfig) ProtoMessage()    {}
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{4}
}

func (m *BuildConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildConfig.Unmarshal(m, b)
}
func (m *BuildConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildConfig.Marshal(b, m, deterministic)
}
func (m *BuildConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildConfig.Merge(m, src)
}
func (m *BuildConfig) XXX_Size() int {
	return xxx_messageInfo_BuildConfig.Size(m)
}
func (m *BuildConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildConfig proto.InternalMessageInfo

func (m *BuildConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuildConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *BuildConfig) GetLanguage() BuildConfig_Language {
	if m != nil {
		return m.Language
	}
	return BuildConfig_NOT_SET
}

func (m *BuildConfig) GetLanguageVersion() string {
	if m != nil {
		return m.LanguageVersion
	}
	return ""
}

func (m *BuildConfig) GetBuildCommand() string {
	if m != nil {
		return m.BuildCommand
	}
	return ""
}

func (m *BuildConfig) GetRunCommand() string {
	if m != nil {
		return m.RunCommand
	}
	return ""
}

func (m *BuildConfig) GetPathToCode() string {
	if m != nil {
		return m.PathToCode
	}
	return ""
}

func (m *BuildConfig) GetPathToStaticOutput() string {
	if m != nil {
		return m.PathToStaticOutput
	}
	return ""
}

func (m *BuildConfig) GetDockerfileFileName() string {
	if m != nil {
		return m.DockerfileFileName
	}
	return ""
}

func (m *BuildConfig) GetBuildArgs() map[string]string {
	if m != nil {
		return m.BuildArgs
	}
	return nil
}

func (m *BuildConfig) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type RunConfig struct {
	Type                    Block_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=Block_Type" json:"type,omitempty"`
	Port                    string             `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	AutoScaling             *AutoScaling       `protobuf:"bytes,3,opt,name=autoScaling,proto3" json:"autoScaling,omitempty"`
	EnvVars                 map[string]string  `protobuf:"bytes,4,rep,name=envVars,proto3" json:"envVars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources               *Resources         `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	TimeoutInSec            int32              `protobuf:"varint,6,opt,name=timeoutInSec,proto3" json:"timeoutInSec,omitempty"`
	JobSpec                 *JobSpec           `protobuf:"bytes,7,opt,name=jobSpec,proto3" json:"jobSpec,omitempty"`
	Host                    string             `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	CostOptimizationEnabled bool               `protobuf:"varint,9,opt,name=costOptimizationEnabled,proto3" json:"costOptimizationEnabled,omitempty"`
	SleepModeEnabled        bool               `protobuf:"varint,10,opt,name=sleepModeEnabled,proto3" json:"sleepModeEnabled,omitempty"`
	Protocol                RunConfig_Protocol `protobuf:"varint,11,opt,name=protocol,proto3,enum=RunConfig_Protocol" json:"protocol,omitempty"`
	SleepModeTTLSeconds     int32              `protobuf:"varint,12,opt,name=sleepModeTTLSeconds,proto3" json:"sleepModeTTLSeconds,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}           `json:"-"`
	XXX_unrecognized        []byte             `json:"-"`
	XXX_sizecache           int32              `json:"-"`
}

func (m *RunConfig) Reset()         { *m = RunConfig{} }
func (m *RunConfig) String() string { return proto.CompactTextString(m) }
func (*RunConfig) ProtoMessage()    {}
func (*RunConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{5}
}

func (m *RunConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunConfig.Unmarshal(m, b)
}
func (m *RunConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunConfig.Marshal(b, m, deterministic)
}
func (m *RunConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunConfig.Merge(m, src)
}
func (m *RunConfig) XXX_Size() int {
	return xxx_messageInfo_RunConfig.Size(m)
}
func (m *RunConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RunConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RunConfig proto.InternalMessageInfo

func (m *RunConfig) GetType() Block_Type {
	if m != nil {
		return m.Type
	}
	return Block_NOT_SET
}

func (m *RunConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *RunConfig) GetAutoScaling() *AutoScaling {
	if m != nil {
		return m.AutoScaling
	}
	return nil
}

func (m *RunConfig) GetEnvVars() map[string]string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *RunConfig) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *RunConfig) GetTimeoutInSec() int32 {
	if m != nil {
		return m.TimeoutInSec
	}
	return 0
}

func (m *RunConfig) GetJobSpec() *JobSpec {
	if m != nil {
		return m.JobSpec
	}
	return nil
}

func (m *RunConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RunConfig) GetCostOptimizationEnabled() bool {
	if m != nil {
		return m.CostOptimizationEnabled
	}
	return false
}

func (m *RunConfig) GetSleepModeEnabled() bool {
	if m != nil {
		return m.SleepModeEnabled
	}
	return false
}

func (m *RunConfig) GetProtocol() RunConfig_Protocol {
	if m != nil {
		return m.Protocol
	}
	return RunConfig_NOT_SET
}

func (m *RunConfig) GetSleepModeTTLSeconds() int32 {
	if m != nil {
		return m.SleepModeTTLSeconds
	}
	return 0
}

type Repository struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Branch               string   `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	GithubInstallationId string   `protobuf:"bytes,4,opt,name=githubInstallationId,proto3" json:"githubInstallationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{6}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Repository) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Repository) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Repository) GetGithubInstallationId() string {
	if m != nil {
		return m.GithubInstallationId
	}
	return ""
}

type JobSpec struct {
	CronPattern          string   `protobuf:"bytes,1,opt,name=cronPattern,proto3" json:"cronPattern,omitempty"`
	TimeoutInSec         int32    `protobuf:"varint,2,opt,name=timeoutInSec,proto3" json:"timeoutInSec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobSpec) Reset()         { *m = JobSpec{} }
func (m *JobSpec) String() string { return proto.CompactTextString(m) }
func (*JobSpec) ProtoMessage()    {}
func (*JobSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{7}
}

func (m *JobSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSpec.Unmarshal(m, b)
}
func (m *JobSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSpec.Marshal(b, m, deterministic)
}
func (m *JobSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSpec.Merge(m, src)
}
func (m *JobSpec) XXX_Size() int {
	return xxx_messageInfo_JobSpec.Size(m)
}
func (m *JobSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSpec.DiscardUnknown(m)
}

var xxx_messageInfo_JobSpec proto.InternalMessageInfo

func (m *JobSpec) GetCronPattern() string {
	if m != nil {
		return m.CronPattern
	}
	return ""
}

func (m *JobSpec) GetTimeoutInSec() int32 {
	if m != nil {
		return m.TimeoutInSec
	}
	return 0
}

type AutoScaling struct {
	Min                  int32    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	CpuPercent           int32    `protobuf:"varint,3,opt,name=cpuPercent,proto3" json:"cpuPercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoScaling) Reset()         { *m = AutoScaling{} }
func (m *AutoScaling) String() string { return proto.CompactTextString(m) }
func (*AutoScaling) ProtoMessage()    {}
func (*AutoScaling) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{8}
}

func (m *AutoScaling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoScaling.Unmarshal(m, b)
}
func (m *AutoScaling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoScaling.Marshal(b, m, deterministic)
}
func (m *AutoScaling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoScaling.Merge(m, src)
}
func (m *AutoScaling) XXX_Size() int {
	return xxx_messageInfo_AutoScaling.Size(m)
}
func (m *AutoScaling) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoScaling.DiscardUnknown(m)
}

var xxx_messageInfo_AutoScaling proto.InternalMessageInfo

func (m *AutoScaling) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *AutoScaling) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *AutoScaling) GetCpuPercent() int32 {
	if m != nil {
		return m.CpuPercent
	}
	return 0
}

type Resources struct {
	MemoryInMB           int32    `protobuf:"varint,1,opt,name=memoryInMB,proto3" json:"memoryInMB,omitempty"`
	CpuInCore            float32  `protobuf:"fixed32,2,opt,name=cpuInCore,proto3" json:"cpuInCore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{9}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetMemoryInMB() int32 {
	if m != nil {
		return m.MemoryInMB
	}
	return 0
}

func (m *Resources) GetCpuInCore() float32 {
	if m != nil {
		return m.CpuInCore
	}
	return 0
}

type Status struct {
	State                Status_State `protobuf:"varint,2,opt,name=state,proto3,enum=Status_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{10}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetState() Status_State {
	if m != nil {
		return m.State
	}
	return Status_NOT_SET
}

type ReleasesStatus struct {
	BlockName            string             `protobuf:"bytes,1,opt,name=blockName,proto3" json:"blockName,omitempty"`
	EnvId                string             `protobuf:"bytes,2,opt,name=envId,proto3" json:"envId,omitempty"`
	Releases             map[string]*Status `protobuf:"bytes,3,rep,name=releases,proto3" json:"releases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReleasesStatus) Reset()         { *m = ReleasesStatus{} }
func (m *ReleasesStatus) String() string { return proto.CompactTextString(m) }
func (*ReleasesStatus) ProtoMessage()    {}
func (*ReleasesStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{11}
}

func (m *ReleasesStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasesStatus.Unmarshal(m, b)
}
func (m *ReleasesStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasesStatus.Marshal(b, m, deterministic)
}
func (m *ReleasesStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasesStatus.Merge(m, src)
}
func (m *ReleasesStatus) XXX_Size() int {
	return xxx_messageInfo_ReleasesStatus.Size(m)
}
func (m *ReleasesStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasesStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasesStatus proto.InternalMessageInfo

func (m *ReleasesStatus) GetBlockName() string {
	if m != nil {
		return m.BlockName
	}
	return ""
}

func (m *ReleasesStatus) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *ReleasesStatus) GetReleases() map[string]*Status {
	if m != nil {
		return m.Releases
	}
	return nil
}

type BuildStatus struct {
	State                BuildStatus_State    `protobuf:"varint,1,opt,name=state,proto3,enum=BuildStatus_State" json:"state,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	FinishTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=finishTime,proto3" json:"finishTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuildStatus) Reset()         { *m = BuildStatus{} }
func (m *BuildStatus) String() string { return proto.CompactTextString(m) }
func (*BuildStatus) ProtoMessage()    {}
func (*BuildStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{12}
}

func (m *BuildStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildStatus.Unmarshal(m, b)
}
func (m *BuildStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildStatus.Marshal(b, m, deterministic)
}
func (m *BuildStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildStatus.Merge(m, src)
}
func (m *BuildStatus) XXX_Size() int {
	return xxx_messageInfo_BuildStatus.Size(m)
}
func (m *BuildStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BuildStatus proto.InternalMessageInfo

func (m *BuildStatus) GetState() BuildStatus_State {
	if m != nil {
		return m.State
	}
	return BuildStatus_NOT_SET
}

func (m *BuildStatus) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *BuildStatus) GetFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

type ConsoleLog struct {
	InstanceName         string   `protobuf:"bytes,1,opt,name=instanceName,proto3" json:"instanceName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsoleLog) Reset()         { *m = ConsoleLog{} }
func (m *ConsoleLog) String() string { return proto.CompactTextString(m) }
func (*ConsoleLog) ProtoMessage()    {}
func (*ConsoleLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{13}
}

func (m *ConsoleLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsoleLog.Unmarshal(m, b)
}
func (m *ConsoleLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsoleLog.Marshal(b, m, deterministic)
}
func (m *ConsoleLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsoleLog.Merge(m, src)
}
func (m *ConsoleLog) XXX_Size() int {
	return xxx_messageInfo_ConsoleLog.Size(m)
}
func (m *ConsoleLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsoleLog.DiscardUnknown(m)
}

var xxx_messageInfo_ConsoleLog proto.InternalMessageInfo

func (m *ConsoleLog) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *ConsoleLog) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlockStatus struct {
	BlockName            string            `protobuf:"bytes,1,opt,name=blockName,proto3" json:"blockName,omitempty"`
	EnvId                string            `protobuf:"bytes,2,opt,name=envId,proto3" json:"envId,omitempty"`
	ReleaseId            string            `protobuf:"bytes,3,opt,name=releaseId,proto3" json:"releaseId,omitempty"`
	State                BlockStatus_State `protobuf:"varint,7,opt,name=state,proto3,enum=BlockStatus_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BlockStatus) Reset()         { *m = BlockStatus{} }
func (m *BlockStatus) String() string { return proto.CompactTextString(m) }
func (*BlockStatus) ProtoMessage()    {}
func (*BlockStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{14}
}

func (m *BlockStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStatus.Unmarshal(m, b)
}
func (m *BlockStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStatus.Marshal(b, m, deterministic)
}
func (m *BlockStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStatus.Merge(m, src)
}
func (m *BlockStatus) XXX_Size() int {
	return xxx_messageInfo_BlockStatus.Size(m)
}
func (m *BlockStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStatus proto.InternalMessageInfo

func (m *BlockStatus) GetBlockName() string {
	if m != nil {
		return m.BlockName
	}
	return ""
}

func (m *BlockStatus) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *BlockStatus) GetReleaseId() string {
	if m != nil {
		return m.ReleaseId
	}
	return ""
}

func (m *BlockStatus) GetState() BlockStatus_State {
	if m != nil {
		return m.State
	}
	return BlockStatus_NOT_SET
}

type BlockStatuses struct {
	BlockStatuses        []*BlockStatus `protobuf:"bytes,1,rep,name=blockStatuses,proto3" json:"blockStatuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockStatuses) Reset()         { *m = BlockStatuses{} }
func (m *BlockStatuses) String() string { return proto.CompactTextString(m) }
func (*BlockStatuses) ProtoMessage()    {}
func (*BlockStatuses) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{15}
}

func (m *BlockStatuses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStatuses.Unmarshal(m, b)
}
func (m *BlockStatuses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStatuses.Marshal(b, m, deterministic)
}
func (m *BlockStatuses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStatuses.Merge(m, src)
}
func (m *BlockStatuses) XXX_Size() int {
	return xxx_messageInfo_BlockStatuses.Size(m)
}
func (m *BlockStatuses) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStatuses.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStatuses proto.InternalMessageInfo

func (m *BlockStatuses) GetBlockStatuses() []*BlockStatus {
	if m != nil {
		return m.BlockStatuses
	}
	return nil
}

type BlockMetrics struct {
	BlockName            string                    `protobuf:"bytes,1,opt,name=blockName,proto3" json:"blockName,omitempty"`
	EnvId                string                    `protobuf:"bytes,2,opt,name=envId,proto3" json:"envId,omitempty"`
	Instances            map[string]*BlockInstance `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Storages             map[string]*BlockStorage  `protobuf:"bytes,5,rep,name=storages,proto3" json:"storages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BlockMetrics) Reset()         { *m = BlockMetrics{} }
func (m *BlockMetrics) String() string { return proto.CompactTextString(m) }
func (*BlockMetrics) ProtoMessage()    {}
func (*BlockMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{16}
}

func (m *BlockMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetrics.Unmarshal(m, b)
}
func (m *BlockMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetrics.Marshal(b, m, deterministic)
}
func (m *BlockMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetrics.Merge(m, src)
}
func (m *BlockMetrics) XXX_Size() int {
	return xxx_messageInfo_BlockMetrics.Size(m)
}
func (m *BlockMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetrics proto.InternalMessageInfo

func (m *BlockMetrics) GetBlockName() string {
	if m != nil {
		return m.BlockName
	}
	return ""
}

func (m *BlockMetrics) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *BlockMetrics) GetInstances() map[string]*BlockInstance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *BlockMetrics) GetStorages() map[string]*BlockStorage {
	if m != nil {
		return m.Storages
	}
	return nil
}

type BlockInstance struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReleaseId            string              `protobuf:"bytes,2,opt,name=releaseId,proto3" json:"releaseId,omitempty"`
	CpuRequests          int64               `protobuf:"varint,3,opt,name=cpuRequests,proto3" json:"cpuRequests,omitempty"`
	CpuUsage             int64               `protobuf:"varint,4,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	MemRequests          int64               `protobuf:"varint,5,opt,name=memRequests,proto3" json:"memRequests,omitempty"`
	MemUsage             int64               `protobuf:"varint,6,opt,name=memUsage,proto3" json:"memUsage,omitempty"`
	Restarts             int32               `protobuf:"varint,7,opt,name=restarts,proto3" json:"restarts,omitempty"`
	State                BlockInstance_State `protobuf:"varint,8,opt,name=state,proto3,enum=BlockInstance_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BlockInstance) Reset()         { *m = BlockInstance{} }
func (m *BlockInstance) String() string { return proto.CompactTextString(m) }
func (*BlockInstance) ProtoMessage()    {}
func (*BlockInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{17}
}

func (m *BlockInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInstance.Unmarshal(m, b)
}
func (m *BlockInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInstance.Marshal(b, m, deterministic)
}
func (m *BlockInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInstance.Merge(m, src)
}
func (m *BlockInstance) XXX_Size() int {
	return xxx_messageInfo_BlockInstance.Size(m)
}
func (m *BlockInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInstance.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInstance proto.InternalMessageInfo

func (m *BlockInstance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BlockInstance) GetReleaseId() string {
	if m != nil {
		return m.ReleaseId
	}
	return ""
}

func (m *BlockInstance) GetCpuRequests() int64 {
	if m != nil {
		return m.CpuRequests
	}
	return 0
}

func (m *BlockInstance) GetCpuUsage() int64 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *BlockInstance) GetMemRequests() int64 {
	if m != nil {
		return m.MemRequests
	}
	return 0
}

func (m *BlockInstance) GetMemUsage() int64 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *BlockInstance) GetRestarts() int32 {
	if m != nil {
		return m.Restarts
	}
	return 0
}

func (m *BlockInstance) GetState() BlockInstance_State {
	if m != nil {
		return m.State
	}
	return BlockInstance_NOT_SET
}

type BlockStorage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CapacityInBytes      int64    `protobuf:"varint,2,opt,name=capacityInBytes,proto3" json:"capacityInBytes,omitempty"`
	UsagePercent         string   `protobuf:"bytes,3,opt,name=usagePercent,proto3" json:"usagePercent,omitempty"`
	MountPath            string   `protobuf:"bytes,4,opt,name=mountPath,proto3" json:"mountPath,omitempty"`
	InstanceId           string   `protobuf:"bytes,5,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockStorage) Reset()         { *m = BlockStorage{} }
func (m *BlockStorage) String() string { return proto.CompactTextString(m) }
func (*BlockStorage) ProtoMessage()    {}
func (*BlockStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{18}
}

func (m *BlockStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStorage.Unmarshal(m, b)
}
func (m *BlockStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStorage.Marshal(b, m, deterministic)
}
func (m *BlockStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStorage.Merge(m, src)
}
func (m *BlockStorage) XXX_Size() int {
	return xxx_messageInfo_BlockStorage.Size(m)
}
func (m *BlockStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStorage.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStorage proto.InternalMessageInfo

func (m *BlockStorage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BlockStorage) GetCapacityInBytes() int64 {
	if m != nil {
		return m.CapacityInBytes
	}
	return 0
}

func (m *BlockStorage) GetUsagePercent() string {
	if m != nil {
		return m.UsagePercent
	}
	return ""
}

func (m *BlockStorage) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

func (m *BlockStorage) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type BlocksMetrics struct {
	Blocks               map[string]*BlockMetrics `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BlocksMetrics) Reset()         { *m = BlocksMetrics{} }
func (m *BlocksMetrics) String() string { return proto.CompactTextString(m) }
func (*BlocksMetrics) ProtoMessage()    {}
func (*BlocksMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{19}
}

func (m *BlocksMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksMetrics.Unmarshal(m, b)
}
func (m *BlocksMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksMetrics.Marshal(b, m, deterministic)
}
func (m *BlocksMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksMetrics.Merge(m, src)
}
func (m *BlocksMetrics) XXX_Size() int {
	return xxx_messageInfo_BlocksMetrics.Size(m)
}
func (m *BlocksMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksMetrics proto.InternalMessageInfo

func (m *BlocksMetrics) GetBlocks() map[string]*BlockMetrics {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Language struct {
	Language             BuildConfig_Language `protobuf:"varint,1,opt,name=language,proto3,enum=BuildConfig_Language" json:"language,omitempty"`
	Image                string               `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	VersionsTags         map[string]string    `protobuf:"bytes,3,rep,name=versionsTags,proto3" json:"versionsTags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Language) Reset()         { *m = Language{} }
func (m *Language) String() string { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()    {}
func (*Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{20}
}

func (m *Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Language.Unmarshal(m, b)
}
func (m *Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Language.Marshal(b, m, deterministic)
}
func (m *Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Language.Merge(m, src)
}
func (m *Language) XXX_Size() int {
	return xxx_messageInfo_Language.Size(m)
}
func (m *Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Language proto.InternalMessageInfo

func (m *Language) GetLanguage() BuildConfig_Language {
	if m != nil {
		return m.Language
	}
	return BuildConfig_NOT_SET
}

func (m *Language) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Language) GetVersionsTags() map[string]string {
	if m != nil {
		return m.VersionsTags
	}
	return nil
}

type MemoryOptions struct {
	DefaultValue         int32    `protobuf:"varint,1,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Values               []int32  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryOptions) Reset()         { *m = MemoryOptions{} }
func (m *MemoryOptions) String() string { return proto.CompactTextString(m) }
func (*MemoryOptions) ProtoMessage()    {}
func (*MemoryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{21}
}

func (m *MemoryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryOptions.Unmarshal(m, b)
}
func (m *MemoryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryOptions.Marshal(b, m, deterministic)
}
func (m *MemoryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryOptions.Merge(m, src)
}
func (m *MemoryOptions) XXX_Size() int {
	return xxx_messageInfo_MemoryOptions.Size(m)
}
func (m *MemoryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryOptions proto.InternalMessageInfo

func (m *MemoryOptions) GetDefaultValue() int32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *MemoryOptions) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type CPUOptions struct {
	DefaultValue         float32   `protobuf:"fixed32,1,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Values               []float32 `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CPUOptions) Reset()         { *m = CPUOptions{} }
func (m *CPUOptions) String() string { return proto.CompactTextString(m) }
func (*CPUOptions) ProtoMessage()    {}
func (*CPUOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{22}
}

func (m *CPUOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPUOptions.Unmarshal(m, b)
}
func (m *CPUOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPUOptions.Marshal(b, m, deterministic)
}
func (m *CPUOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUOptions.Merge(m, src)
}
func (m *CPUOptions) XXX_Size() int {
	return xxx_messageInfo_CPUOptions.Size(m)
}
func (m *CPUOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CPUOptions proto.InternalMessageInfo

func (m *CPUOptions) GetDefaultValue() float32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *CPUOptions) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type TimeoutOptions struct {
	DefaultValue         int32    `protobuf:"varint,1,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Values               []int32  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeoutOptions) Reset()         { *m = TimeoutOptions{} }
func (m *TimeoutOptions) String() string { return proto.CompactTextString(m) }
func (*TimeoutOptions) ProtoMessage()    {}
func (*TimeoutOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{23}
}

func (m *TimeoutOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeoutOptions.Unmarshal(m, b)
}
func (m *TimeoutOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeoutOptions.Marshal(b, m, deterministic)
}
func (m *TimeoutOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeoutOptions.Merge(m, src)
}
func (m *TimeoutOptions) XXX_Size() int {
	return xxx_messageInfo_TimeoutOptions.Size(m)
}
func (m *TimeoutOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeoutOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TimeoutOptions proto.InternalMessageInfo

func (m *TimeoutOptions) GetDefaultValue() int32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *TimeoutOptions) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type AutoScalingOptions struct {
	DefaultMinValue      int32    `protobuf:"varint,1,opt,name=defaultMinValue,proto3" json:"defaultMinValue,omitempty"`
	DefaultMaxValue      int32    `protobuf:"varint,2,opt,name=defaultMaxValue,proto3" json:"defaultMaxValue,omitempty"`
	Values               []int32  `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoScalingOptions) Reset()         { *m = AutoScalingOptions{} }
func (m *AutoScalingOptions) String() string { return proto.CompactTextString(m) }
func (*AutoScalingOptions) ProtoMessage()    {}
func (*AutoScalingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{24}
}

func (m *AutoScalingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoScalingOptions.Unmarshal(m, b)
}
func (m *AutoScalingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoScalingOptions.Marshal(b, m, deterministic)
}
func (m *AutoScalingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoScalingOptions.Merge(m, src)
}
func (m *AutoScalingOptions) XXX_Size() int {
	return xxx_messageInfo_AutoScalingOptions.Size(m)
}
func (m *AutoScalingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoScalingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AutoScalingOptions proto.InternalMessageInfo

func (m *AutoScalingOptions) GetDefaultMinValue() int32 {
	if m != nil {
		return m.DefaultMinValue
	}
	return 0
}

func (m *AutoScalingOptions) GetDefaultMaxValue() int32 {
	if m != nil {
		return m.DefaultMaxValue
	}
	return 0
}

func (m *AutoScalingOptions) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type KintoConfiguration struct {
	Languages            []*Language         `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	MemoryOptions        *MemoryOptions      `protobuf:"bytes,2,opt,name=memoryOptions,proto3" json:"memoryOptions,omitempty"`
	CpuOptions           *CPUOptions         `protobuf:"bytes,3,opt,name=cpuOptions,proto3" json:"cpuOptions,omitempty"`
	TimeoutOptions       *TimeoutOptions     `protobuf:"bytes,4,opt,name=timeoutOptions,proto3" json:"timeoutOptions,omitempty"`
	AutoScalingOptions   *AutoScalingOptions `protobuf:"bytes,5,opt,name=autoScalingOptions,proto3" json:"autoScalingOptions,omitempty"`
	JobTimeoutOptions    *TimeoutOptions     `protobuf:"bytes,6,opt,name=jobTimeoutOptions,proto3" json:"jobTimeoutOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *KintoConfiguration) Reset()         { *m = KintoConfiguration{} }
func (m *KintoConfiguration) String() string { return proto.CompactTextString(m) }
func (*KintoConfiguration) ProtoMessage()    {}
func (*KintoConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{25}
}

func (m *KintoConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KintoConfiguration.Unmarshal(m, b)
}
func (m *KintoConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KintoConfiguration.Marshal(b, m, deterministic)
}
func (m *KintoConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KintoConfiguration.Merge(m, src)
}
func (m *KintoConfiguration) XXX_Size() int {
	return xxx_messageInfo_KintoConfiguration.Size(m)
}
func (m *KintoConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_KintoConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_KintoConfiguration proto.InternalMessageInfo

func (m *KintoConfiguration) GetLanguages() []*Language {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *KintoConfiguration) GetMemoryOptions() *MemoryOptions {
	if m != nil {
		return m.MemoryOptions
	}
	return nil
}

func (m *KintoConfiguration) GetCpuOptions() *CPUOptions {
	if m != nil {
		return m.CpuOptions
	}
	return nil
}

func (m *KintoConfiguration) GetTimeoutOptions() *TimeoutOptions {
	if m != nil {
		return m.TimeoutOptions
	}
	return nil
}

func (m *KintoConfiguration) GetAutoScalingOptions() *AutoScalingOptions {
	if m != nil {
		return m.AutoScalingOptions
	}
	return nil
}

func (m *KintoConfiguration) GetJobTimeoutOptions() *TimeoutOptions {
	if m != nil {
		return m.JobTimeoutOptions
	}
	return nil
}

type Logs struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logs) Reset()         { *m = Logs{} }
func (m *Logs) String() string { return proto.CompactTextString(m) }
func (*Logs) ProtoMessage()    {}
func (*Logs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{26}
}

func (m *Logs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logs.Unmarshal(m, b)
}
func (m *Logs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logs.Marshal(b, m, deterministic)
}
func (m *Logs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logs.Merge(m, src)
}
func (m *Logs) XXX_Size() int {
	return xxx_messageInfo_Logs.Size(m)
}
func (m *Logs) XXX_DiscardUnknown() {
	xxx_messageInfo_Logs.DiscardUnknown(m)
}

var xxx_messageInfo_Logs proto.InternalMessageInfo

func (m *Logs) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccessTokenData struct {
	ClusterAccess        *AccessPermission `protobuf:"bytes,1,opt,name=clusterAccess,proto3" json:"clusterAccess,omitempty"`
	EnvironmentAccess    *AccessPermission `protobuf:"bytes,2,opt,name=environmentAccess,proto3" json:"environmentAccess,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccessTokenData) Reset()         { *m = AccessTokenData{} }
func (m *AccessTokenData) String() string { return proto.CompactTextString(m) }
func (*AccessTokenData) ProtoMessage()    {}
func (*AccessTokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{27}
}

func (m *AccessTokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenData.Unmarshal(m, b)
}
func (m *AccessTokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenData.Marshal(b, m, deterministic)
}
func (m *AccessTokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenData.Merge(m, src)
}
func (m *AccessTokenData) XXX_Size() int {
	return xxx_messageInfo_AccessTokenData.Size(m)
}
func (m *AccessTokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenData.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenData proto.InternalMessageInfo

func (m *AccessTokenData) GetClusterAccess() *AccessPermission {
	if m != nil {
		return m.ClusterAccess
	}
	return nil
}

func (m *AccessTokenData) GetEnvironmentAccess() *AccessPermission {
	if m != nil {
		return m.EnvironmentAccess
	}
	return nil
}

func (m *AccessTokenData) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type AccessPermission struct {
	ResourceId           string                `protobuf:"bytes,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	Role                 AccessPermission_Role `protobuf:"varint,2,opt,name=role,proto3,enum=AccessPermission_Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AccessPermission) Reset()         { *m = AccessPermission{} }
func (m *AccessPermission) String() string { return proto.CompactTextString(m) }
func (*AccessPermission) ProtoMessage()    {}
func (*AccessPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{28}
}

func (m *AccessPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessPermission.Unmarshal(m, b)
}
func (m *AccessPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessPermission.Marshal(b, m, deterministic)
}
func (m *AccessPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessPermission.Merge(m, src)
}
func (m *AccessPermission) XXX_Size() int {
	return xxx_messageInfo_AccessPermission.Size(m)
}
func (m *AccessPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessPermission.DiscardUnknown(m)
}

var xxx_messageInfo_AccessPermission proto.InternalMessageInfo

func (m *AccessPermission) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *AccessPermission) GetRole() AccessPermission_Role {
	if m != nil {
		return m.Role
	}
	return AccessPermission_NOT_SET
}

type ClusterSecretData struct {
	ClusterId                   string   `protobuf:"bytes,1,opt,name=ClusterId,proto3" json:"ClusterId,omitempty"`
	ClusterClientSecret         string   `protobuf:"bytes,2,opt,name=ClusterClientSecret,proto3" json:"ClusterClientSecret,omitempty"`
	ClusterAccessTokenSecretKey []byte   `protobuf:"bytes,3,opt,name=ClusterAccessTokenSecretKey,proto3" json:"ClusterAccessTokenSecretKey,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *ClusterSecretData) Reset()         { *m = ClusterSecretData{} }
func (m *ClusterSecretData) String() string { return proto.CompactTextString(m) }
func (*ClusterSecretData) ProtoMessage()    {}
func (*ClusterSecretData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{29}
}

func (m *ClusterSecretData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterSecretData.Unmarshal(m, b)
}
func (m *ClusterSecretData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterSecretData.Marshal(b, m, deterministic)
}
func (m *ClusterSecretData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterSecretData.Merge(m, src)
}
func (m *ClusterSecretData) XXX_Size() int {
	return xxx_messageInfo_ClusterSecretData.Size(m)
}
func (m *ClusterSecretData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterSecretData.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterSecretData proto.InternalMessageInfo

func (m *ClusterSecretData) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ClusterSecretData) GetClusterClientSecret() string {
	if m != nil {
		return m.ClusterClientSecret
	}
	return ""
}

func (m *ClusterSecretData) GetClusterAccessTokenSecretKey() []byte {
	if m != nil {
		return m.ClusterAccessTokenSecretKey
	}
	return nil
}

type JobStatus struct {
	InstanceName         string          `protobuf:"bytes,1,opt,name=instanceName,proto3" json:"instanceName,omitempty"`
	State                JobStatus_State `protobuf:"varint,2,opt,name=state,proto3,enum=JobStatus_State" json:"state,omitempty"`
	StartTimestamp       int64           `protobuf:"varint,3,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp         int64           `protobuf:"varint,4,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{30}
}

func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (m *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(m, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func (m *JobStatus) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *JobStatus) GetState() JobStatus_State {
	if m != nil {
		return m.State
	}
	return JobStatus_NOT_SET
}

func (m *JobStatus) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *JobStatus) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

type TeleportServiceData struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Credentials          string   `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeleportServiceData) Reset()         { *m = TeleportServiceData{} }
func (m *TeleportServiceData) String() string { return proto.CompactTextString(m) }
func (*TeleportServiceData) ProtoMessage()    {}
func (*TeleportServiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1289d738234000eb, []int{31}
}

func (m *TeleportServiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeleportServiceData.Unmarshal(m, b)
}
func (m *TeleportServiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeleportServiceData.Marshal(b, m, deterministic)
}
func (m *TeleportServiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeleportServiceData.Merge(m, src)
}
func (m *TeleportServiceData) XXX_Size() int {
	return xxx_messageInfo_TeleportServiceData.Size(m)
}
func (m *TeleportServiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_TeleportServiceData.DiscardUnknown(m)
}

var xxx_messageInfo_TeleportServiceData proto.InternalMessageInfo

func (m *TeleportServiceData) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *TeleportServiceData) GetCredentials() string {
	if m != nil {
		return m.Credentials
	}
	return ""
}

func init() {
	proto.RegisterEnum("Block_Type", Block_Type_name, Block_Type_value)
	proto.RegisterEnum("Release_Type", Release_Type_name, Release_Type_value)
	proto.RegisterEnum("BuildConfig_Language", BuildConfig_Language_name, BuildConfig_Language_value)
	proto.RegisterEnum("RunConfig_Protocol", RunConfig_Protocol_name, RunConfig_Protocol_value)
	proto.RegisterEnum("Status_State", Status_State_name, Status_State_value)
	proto.RegisterEnum("BuildStatus_State", BuildStatus_State_name, BuildStatus_State_value)
	proto.RegisterEnum("BlockStatus_State", BlockStatus_State_name, BlockStatus_State_value)
	proto.RegisterEnum("BlockInstance_State", BlockInstance_State_name, BlockInstance_State_value)
	proto.RegisterEnum("AccessPermission_Role", AccessPermission_Role_name, AccessPermission_Role_value)
	proto.RegisterEnum("JobStatus_State", JobStatus_State_name, JobStatus_State_value)
	proto.RegisterType((*Environment)(nil), "Environment")
	proto.RegisterType((*Blocks)(nil), "Blocks")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterMapType((map[string]*Release)(nil), "Block.ReleasesEntry")
	proto.RegisterType((*Release)(nil), "Release")
	proto.RegisterType((*BuildConfig)(nil), "BuildConfig")
	proto.RegisterMapType((map[string]string)(nil), "BuildConfig.BuildArgsEntry")
	proto.RegisterType((*RunConfig)(nil), "RunConfig")
	proto.RegisterMapType((map[string]string)(nil), "RunConfig.EnvVarsEntry")
	proto.RegisterType((*Repository)(nil), "Repository")
	proto.RegisterType((*JobSpec)(nil), "JobSpec")
	proto.RegisterType((*AutoScaling)(nil), "AutoScaling")
	proto.RegisterType((*Resources)(nil), "Resources")
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*ReleasesStatus)(nil), "ReleasesStatus")
	proto.RegisterMapType((map[string]*Status)(nil), "ReleasesStatus.ReleasesEntry")
	proto.RegisterType((*BuildStatus)(nil), "BuildStatus")
	proto.RegisterType((*ConsoleLog)(nil), "ConsoleLog")
	proto.RegisterType((*BlockStatus)(nil), "BlockStatus")
	proto.RegisterType((*BlockStatuses)(nil), "BlockStatuses")
	proto.RegisterType((*BlockMetrics)(nil), "BlockMetrics")
	proto.RegisterMapType((map[string]*BlockInstance)(nil), "BlockMetrics.InstancesEntry")
	proto.RegisterMapType((map[string]*BlockStorage)(nil), "BlockMetrics.StoragesEntry")
	proto.RegisterType((*BlockInstance)(nil), "BlockInstance")
	proto.RegisterType((*BlockStorage)(nil), "BlockStorage")
	proto.RegisterType((*BlocksMetrics)(nil), "BlocksMetrics")
	proto.RegisterMapType((map[string]*BlockMetrics)(nil), "BlocksMetrics.BlocksEntry")
	proto.RegisterType((*Language)(nil), "Language")
	proto.RegisterMapType((map[string]string)(nil), "Language.VersionsTagsEntry")
	proto.RegisterType((*MemoryOptions)(nil), "MemoryOptions")
	proto.RegisterType((*CPUOptions)(nil), "CPUOptions")
	proto.RegisterType((*TimeoutOptions)(nil), "TimeoutOptions")
	proto.RegisterType((*AutoScalingOptions)(nil), "AutoScalingOptions")
	proto.RegisterType((*KintoConfiguration)(nil), "KintoConfiguration")
	proto.RegisterType((*Logs)(nil), "Logs")
	proto.RegisterType((*AccessTokenData)(nil), "AccessTokenData")
	proto.RegisterMapType((map[string]string)(nil), "AccessTokenData.MetadataEntry")
	proto.RegisterType((*AccessPermission)(nil), "AccessPermission")
	proto.RegisterType((*ClusterSecretData)(nil), "ClusterSecretData")
	proto.RegisterType((*JobStatus)(nil), "JobStatus")
	proto.RegisterType((*TeleportServiceData)(nil), "TeleportServiceData")
}

func init() {
	proto.RegisterFile("kkc_models.proto", fileDescriptor_1289d738234000eb)
}

var fileDescriptor_1289d738234000eb = []byte{
	// 2607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5b, 0x8f, 0xe4, 0x46,
	0x15, 0xc6, 0x7d, 0xf7, 0xe9, 0x99, 0x59, 0x6f, 0xed, 0x92, 0x8c, 0x3a, 0x9b, 0x64, 0x71, 0xa2,
	0x30, 0x4a, 0xc0, 0x9b, 0x0c, 0x91, 0x92, 0x2c, 0xa0, 0xd0, 0x17, 0x67, 0xc7, 0x3b, 0x7d, 0x4b,
	0xb5, 0x7b, 0x36, 0xe1, 0x65, 0xf0, 0xb8, 0x6b, 0x67, 0x9c, 0x71, 0xdb, 0x8d, 0x5d, 0x5e, 0x65,
	0x78, 0x40, 0x3c, 0x20, 0x21, 0x45, 0xf0, 0x80, 0xc4, 0x5f, 0xe0, 0x95, 0xbf, 0x00, 0x3c, 0xf0,
	0x03, 0x40, 0x42, 0x42, 0x42, 0xfc, 0x11, 0x9e, 0x50, 0x5d, 0xec, 0x2e, 0x4f, 0xf7, 0x66, 0x77,
	0x81, 0x27, 0xd7, 0xf9, 0xce, 0x39, 0xe5, 0x72, 0x9d, 0xbb, 0xc1, 0xb8, 0xbc, 0xf4, 0x4f, 0x97,
	0xf1, 0x82, 0x84, 0xa9, 0xb5, 0x4a, 0x62, 0x1a, 0x77, 0x5e, 0x3f, 0x8f, 0xe3, 0xf3, 0x90, 0xdc,
	0xe3, 0xd4, 0x59, 0xf6, 0xf8, 0x1e, 0x0d, 0x96, 0x24, 0xa5, 0xde, 0x72, 0x25, 0x04, 0xcc, 0x57,
	0xa1, 0x6d, 0x47, 0x4f, 0x82, 0x24, 0x8e, 0x96, 0x24, 0xa2, 0x68, 0x0f, 0x2a, 0xc1, 0x62, 0x5f,
	0xbb, 0xab, 0x1d, 0xe8, 0xb8, 0x12, 0x2c, 0xcc, 0xb7, 0xa0, 0xd1, 0x0b, 0x63, 0xff, 0x32, 0x45,
	0x77, 0xa0, 0x1e, 0x50, 0xb2, 0x4c, 0xf7, 0xb5, 0xbb, 0xd5, 0x83, 0xf6, 0x61, 0xc3, 0xe2, 0x38,
	0x16, 0xa0, 0xf9, 0xab, 0x1a, 0xd4, 0x39, 0x70, 0x7d, 0x07, 0x84, 0xa0, 0x16, 0x79, 0x4b, 0xb2,
	0x5f, 0xe1, 0x08, 0x5f, 0xa3, 0xdb, 0x50, 0x27, 0xd1, 0x13, 0x67, 0xb1, 0x5f, 0xe5, 0xa0, 0x20,
	0xd0, 0x5d, 0x68, 0x2f, 0x82, 0x74, 0x15, 0x7a, 0x57, 0x63, 0xa6, 0x50, 0xe3, 0x3c, 0x15, 0x42,
	0xef, 0x42, 0x2b, 0x21, 0x21, 0xf1, 0x52, 0x92, 0xee, 0xd7, 0xf9, 0x31, 0x6e, 0x8b, 0x63, 0x58,
	0x58, 0xc2, 0x76, 0x44, 0x93, 0x2b, 0x5c, 0x48, 0xa1, 0x37, 0x61, 0xd7, 0xcf, 0x52, 0x1a, 0x2f,
	0x07, 0xf1, 0xd2, 0x0b, 0xa2, 0x74, 0xbf, 0x71, 0xb7, 0x7a, 0xa0, 0xe3, 0x32, 0xc8, 0xde, 0x1c,
	0xa4, 0xd3, 0xec, 0x2c, 0x0c, 0xfc, 0x39, 0x1e, 0xee, 0x37, 0xef, 0x6a, 0x07, 0x2d, 0xac, 0x42,
	0xe8, 0x00, 0x6e, 0xac, 0xbc, 0x84, 0x44, 0x94, 0xbf, 0x8e, 0x9f, 0xaf, 0xc5, 0xcf, 0x77, 0x1d,
	0x46, 0x6f, 0x83, 0xa1, 0x40, 0x36, 0xff, 0x4c, 0x9d, 0x8b, 0x6e, 0xe0, 0x1d, 0x1b, 0x76, 0x4b,
	0x07, 0x47, 0x06, 0x54, 0x2f, 0xc9, 0x95, 0xbc, 0x3d, 0xb6, 0x44, 0xaf, 0x41, 0xfd, 0x89, 0x17,
	0x66, 0xe2, 0xfe, 0xda, 0x87, 0xad, 0xfc, 0x4b, 0xb1, 0x80, 0xef, 0x57, 0x3e, 0xd4, 0xcc, 0xaf,
	0x34, 0xa8, 0xb9, 0x57, 0x2b, 0x82, 0xda, 0xd0, 0x1c, 0x4f, 0xdc, 0xd3, 0x99, 0xed, 0x1a, 0xdf,
	0x40, 0x37, 0xa0, 0xdd, 0xeb, 0xf6, 0x8f, 0xed, 0xf1, 0xe0, 0xb4, 0x3b, 0x75, 0x0c, 0x8d, 0x01,
	0x33, 0xb7, 0xeb, 0x3a, 0xfd, 0xd3, 0x99, 0xe3, 0xda, 0x46, 0x85, 0x89, 0x3f, 0xb2, 0x7b, 0xa7,
	0xdd, 0xe9, 0xd4, 0xa8, 0xa2, 0x1d, 0x68, 0x3d, 0xec, 0x8e, 0x66, 0x6e, 0xb7, 0x7f, 0x6c, 0xd4,
	0x50, 0x13, 0xaa, 0x0f, 0x27, 0x3d, 0xa3, 0xce, 0xe0, 0x3e, 0x9e, 0x8c, 0x4f, 0x19, 0xd5, 0x40,
	0x00, 0x8d, 0x47, 0x13, 0x7c, 0x6c, 0x63, 0xa3, 0xc9, 0xb4, 0xfb, 0x5d, 0xb7, 0x3b, 0x9c, 0x3c,
	0x30, 0x5a, 0xa8, 0x05, 0xb5, 0x23, 0x7b, 0x38, 0x32, 0x74, 0xf3, 0x8f, 0x55, 0x68, 0xca, 0x33,
	0x6e, 0xf8, 0xc2, 0x87, 0xa0, 0xfb, 0x09, 0xf1, 0x28, 0x59, 0x74, 0xa9, 0xfc, 0xa0, 0x8e, 0x25,
	0x3c, 0xd4, 0xca, 0x3d, 0xd4, 0x72, 0x73, 0x0f, 0xc5, 0x6b, 0x61, 0x64, 0x41, 0xfb, 0x2c, 0x0b,
	0xc2, 0x45, 0x3f, 0x8e, 0x1e, 0x07, 0xe7, 0xdc, 0x6f, 0xda, 0x87, 0x3b, 0x56, 0x6f, 0x8d, 0x61,
	0x55, 0x00, 0x1d, 0x80, 0x9e, 0x64, 0x91, 0x94, 0xae, 0x71, 0x69, 0xb0, 0x70, 0x8e, 0xe0, 0x35,
	0x13, 0xbd, 0x0e, 0x8d, 0x94, 0x7a, 0x34, 0x63, 0x1e, 0xc5, 0xc4, 0x9a, 0xd6, 0x8c, 0x93, 0x58,
	0xc2, 0xec, 0xd0, 0x29, 0xf5, 0x12, 0x71, 0xe8, 0xc6, 0xb3, 0x0f, 0x5d, 0x08, 0xa3, 0xf7, 0xa1,
	0x49, 0xa2, 0x05, 0xd7, 0x6b, 0x3e, 0x53, 0x2f, 0x17, 0x45, 0xdf, 0x82, 0x1a, 0xbd, 0x5a, 0x09,
	0xff, 0xda, 0x3b, 0xdc, 0xcd, 0x0d, 0x6e, 0x31, 0x0b, 0x63, 0xce, 0x62, 0x31, 0x45, 0xbd, 0xf3,
	0x74, 0x5f, 0xe7, 0xce, 0xcc, 0xd7, 0xe6, 0xd1, 0x36, 0x1f, 0x00, 0x68, 0x0c, 0xec, 0xe9, 0x70,
	0xf2, 0xb9, 0xa1, 0x31, 0x4b, 0xce, 0xc7, 0x92, 0xe2, 0xb6, 0x9f, 0xcd, 0x67, 0x53, 0x7b, 0x3c,
	0x10, 0xb6, 0xc7, 0x93, 0xe1, 0xb0, 0xc7, 0x6d, 0x6f, 0xfe, 0xbb, 0x06, 0x6d, 0xe5, 0x62, 0x37,
	0xac, 0x78, 0x1b, 0xea, 0xc1, 0xd2, 0x3b, 0xcf, 0x43, 0x5a, 0x10, 0xe8, 0x3d, 0x68, 0x85, 0x5e,
	0x74, 0x9e, 0x31, 0x46, 0x95, 0x1f, 0xfd, 0x9b, 0xaa, 0x79, 0xac, 0xa1, 0x64, 0xe2, 0x42, 0x8c,
	0x05, 0x55, 0xbe, 0x3e, 0x21, 0x49, 0x1a, 0xc4, 0x91, 0x0c, 0xfa, 0xeb, 0x30, 0x32, 0x61, 0x47,
	0x5a, 0x77, 0xb9, 0xf4, 0xa2, 0x05, 0x37, 0x95, 0x8e, 0x4b, 0x18, 0x7a, 0x0d, 0x80, 0x5b, 0x55,
	0x48, 0x34, 0xb8, 0x84, 0x82, 0x30, 0xfe, 0xca, 0xa3, 0x17, 0x6e, 0xdc, 0x8f, 0x17, 0x84, 0x1b,
	0x44, 0xc7, 0x0a, 0x82, 0x2c, 0x40, 0x82, 0x62, 0xf6, 0x0f, 0xfc, 0x49, 0x46, 0x57, 0x19, 0xdd,
	0x6f, 0x73, 0xb9, 0x2d, 0x1c, 0x26, 0xbf, 0x88, 0xfd, 0x4b, 0x92, 0x3c, 0x0e, 0x42, 0xf2, 0x49,
	0x10, 0x12, 0x25, 0x2b, 0x6c, 0xe1, 0xa0, 0x8f, 0x40, 0xe7, 0xe7, 0xed, 0x26, 0xd2, 0x72, 0xed,
	0xc3, 0x57, 0x4a, 0x37, 0xd4, 0xcb, 0xb9, 0x22, 0x89, 0xad, 0xa5, 0xd1, 0x3b, 0x00, 0x09, 0x59,
	0xc5, 0x69, 0x40, 0xe3, 0xe4, 0x6a, 0x1f, 0xb8, 0x2f, 0xb5, 0x2d, 0x5c, 0x40, 0x58, 0x61, 0x77,
	0x7e, 0x00, 0x7b, 0xe5, 0x9d, 0xb6, 0x64, 0x95, 0xdb, 0x6a, 0x56, 0xd1, 0xd5, 0x5c, 0xf2, 0x73,
	0x68, 0xe5, 0x96, 0x2a, 0xbb, 0xd2, 0x1e, 0xc0, 0x60, 0xd2, 0x3f, 0xb6, 0xf1, 0x27, 0xce, 0xd0,
	0x36, 0x34, 0xe6, 0x5a, 0x0f, 0x26, 0xc3, 0xee, 0xf8, 0x81, 0x51, 0x61, 0xeb, 0xf1, 0x64, 0x60,
	0x3f, 0x9c, 0x19, 0x55, 0xb6, 0x9e, 0x7e, 0xee, 0x1e, 0x4d, 0xc6, 0x46, 0x8d, 0x65, 0x85, 0x87,
	0xdd, 0x93, 0xae, 0x51, 0x67, 0x2b, 0x3c, 0xef, 0x7d, 0x6e, 0x34, 0x58, 0x66, 0x99, 0x1e, 0x4d,
	0x8d, 0xa6, 0x80, 0x66, 0xae, 0xd1, 0x62, 0x2a, 0xf6, 0xd0, 0xf9, 0xcc, 0xc1, 0x86, 0x6e, 0xfe,
	0xb3, 0x06, 0x3a, 0x56, 0x82, 0x53, 0xc4, 0x82, 0xc6, 0x1d, 0xaa, 0x2d, 0x93, 0x7d, 0x39, 0x12,
	0x56, 0x71, 0x42, 0xf3, 0xea, 0xc2, 0xd6, 0x2c, 0x57, 0x78, 0x19, 0x8d, 0x67, 0xbe, 0x17, 0x06,
	0xd1, 0x3a, 0x57, 0x74, 0xd7, 0x18, 0x56, 0x05, 0xd0, 0x7b, 0x2c, 0x4c, 0x9f, 0x9c, 0x78, 0x49,
	0xba, 0x5f, 0xe3, 0x66, 0x79, 0x79, 0x9d, 0x29, 0x2c, 0x5b, 0x70, 0x84, 0x49, 0x72, 0x39, 0x9e,
	0x5e, 0x48, 0x1a, 0x67, 0x89, 0x4f, 0xf2, 0xbc, 0x01, 0x16, 0xce, 0x11, 0xbc, 0x66, 0x32, 0xcf,
	0x65, 0x25, 0x37, 0xce, 0xa8, 0x13, 0xcd, 0x88, 0xcf, 0xfd, 0xb2, 0x8e, 0x4b, 0x18, 0x32, 0xa1,
	0xf9, 0x45, 0x7c, 0x36, 0x5b, 0x11, 0x5f, 0xe6, 0x89, 0x96, 0xf5, 0x50, 0xd0, 0x38, 0x67, 0xb0,
	0x0f, 0xbd, 0x88, 0x53, 0x2a, 0xfd, 0x8b, 0xaf, 0xd1, 0x87, 0xf0, 0xb2, 0x1f, 0xa7, 0x74, 0xb2,
	0xa2, 0xc1, 0x32, 0xf8, 0x99, 0x47, 0x83, 0x38, 0xb2, 0x23, 0xef, 0x2c, 0x24, 0xa2, 0xe2, 0xb4,
	0xf0, 0xd3, 0xd8, 0xac, 0x48, 0xa5, 0x21, 0x21, 0xab, 0x51, 0xbc, 0x20, 0xb9, 0x0a, 0x70, 0x95,
	0x0d, 0x1c, 0xdd, 0x83, 0x16, 0x4f, 0x57, 0x7e, 0x1c, 0xf2, 0x68, 0xd8, 0x3b, 0xbc, 0xa5, 0xdc,
	0xcf, 0x54, 0xb2, 0x70, 0x21, 0x84, 0xde, 0x85, 0x5b, 0xc5, 0x26, 0xae, 0x3b, 0x9c, 0x11, 0x3f,
	0x8e, 0x16, 0xe9, 0xfe, 0x0e, 0xff, 0xf2, 0x6d, 0xac, 0xce, 0x7d, 0xd8, 0x51, 0xef, 0xf9, 0x85,
	0x1c, 0xf6, 0x1d, 0x68, 0xe5, 0x67, 0x28, 0x3b, 0x2c, 0x2b, 0x49, 0xae, 0x3b, 0x35, 0x34, 0xb6,
	0x7a, 0x80, 0xa7, 0x7d, 0xa3, 0x62, 0xfe, 0x5a, 0x03, 0x58, 0x87, 0x0d, 0x7b, 0x4f, 0x96, 0x84,
	0xf9, 0x7b, 0xb2, 0x24, 0x64, 0x9d, 0x80, 0xe7, 0xfb, 0x24, 0x4d, 0xdd, 0xf8, 0x92, 0x44, 0xf2,
	0x6d, 0x2a, 0x84, 0x5e, 0x82, 0xc6, 0x59, 0xe2, 0x45, 0xfe, 0x85, 0x6c, 0x5e, 0x24, 0x85, 0x0e,
	0xe1, 0xf6, 0x79, 0x40, 0x2f, 0xb2, 0x33, 0x27, 0x4a, 0xa9, 0x17, 0x86, 0xfc, 0xbe, 0x9d, 0x85,
	0xcc, 0x68, 0x5b, 0x79, 0xe6, 0x04, 0x9a, 0xd2, 0xd0, 0xec, 0xc5, 0x7e, 0x12, 0x47, 0x53, 0x8f,
	0x52, 0x92, 0x44, 0xf2, 0x48, 0x2a, 0xb4, 0xe1, 0x49, 0x95, 0x4d, 0x4f, 0x32, 0x3f, 0x85, 0xb6,
	0xe2, 0xe6, 0xec, 0xfb, 0x96, 0x81, 0xd8, 0xac, 0x8e, 0xd9, 0x92, 0x23, 0xde, 0x97, 0x52, 0x97,
	0x2d, 0x59, 0x5a, 0xf4, 0x57, 0xd9, 0x94, 0x24, 0x3e, 0x89, 0x28, 0xff, 0xa6, 0x3a, 0x56, 0x10,
	0xd3, 0x01, 0xbd, 0x70, 0x6c, 0x26, 0xbc, 0x24, 0xcb, 0x38, 0xb9, 0x72, 0xa2, 0x51, 0x4f, 0xee,
	0xab, 0x20, 0xe8, 0x0e, 0xe8, 0xfe, 0x2a, 0x73, 0xa2, 0x7e, 0x9c, 0x08, 0x53, 0x55, 0xf0, 0x1a,
	0x30, 0x7f, 0xa7, 0x41, 0x43, 0x14, 0x57, 0xf4, 0x06, 0xd4, 0x59, 0x79, 0x15, 0x42, 0xac, 0xca,
	0x09, 0x9c, 0x3f, 0x08, 0x16, 0x3c, 0x93, 0x40, 0x9d, 0xd3, 0x1b, 0x76, 0xfd, 0xa4, 0xeb, 0x0c,
	0x0d, 0x4d, 0xd4, 0xb0, 0x7e, 0xdf, 0x9e, 0xcd, 0x44, 0x41, 0xc3, 0xf3, 0xf1, 0xd8, 0x19, 0x3f,
	0x30, 0xaa, 0x8c, 0x60, 0xa5, 0x8d, 0x11, 0x35, 0x46, 0x74, 0x7b, 0x13, 0xec, 0xda, 0x03, 0xa3,
	0x8e, 0x6e, 0xc2, 0x2e, 0xb6, 0x4f, 0x1c, 0xfb, 0xd1, 0xa9, 0x2c, 0x85, 0x0d, 0xf3, 0x2f, 0x1a,
	0xec, 0xe5, 0x6d, 0x98, 0x3c, 0xde, 0x1d, 0xd0, 0xcf, 0x8a, 0x46, 0x4f, 0xd8, 0x62, 0x0d, 0xac,
	0xdb, 0xd7, 0x8a, 0xda, 0xbe, 0x7e, 0xa4, 0x34, 0xa7, 0x55, 0x9e, 0x47, 0x5e, 0xb5, 0xca, 0xdb,
	0x3e, 0xad, 0x4b, 0xed, 0x0c, 0x9e, 0xdd, 0x07, 0xbe, 0x5a, 0xee, 0x03, 0x8b, 0x2e, 0x45, 0x89,
	0x84, 0x3f, 0x57, 0x64, 0xdd, 0x96, 0x1f, 0x71, 0x90, 0xdf, 0xb1, 0xc8, 0x9e, 0xc8, 0x52, 0x98,
	0xa5, 0x8b, 0x2e, 0x5a, 0x1c, 0xd6, 0x8d, 0x3c, 0x4f, 0x5f, 0x56, 0x08, 0xa3, 0xfb, 0x00, 0x8f,
	0x83, 0x28, 0x48, 0x2f, 0xb8, 0x6a, 0xf5, 0x99, 0xaa, 0x8a, 0xb4, 0xf9, 0x5b, 0x6d, 0xab, 0x7d,
	0xdb, 0xd0, 0x9c, 0x8f, 0x8f, 0xc7, 0x93, 0x47, 0x63, 0x51, 0x65, 0x3e, 0x9d, 0xdb, 0x73, 0x7b,
	0x20, 0xdb, 0xd5, 0x09, 0x3e, 0x2e, 0x2c, 0x9c, 0xdb, 0x9e, 0x5b, 0x98, 0xb9, 0xc4, 0x1c, 0xdb,
	0x46, 0x1d, 0x21, 0xd8, 0x73, 0xc6, 0xae, 0x8d, 0xc7, 0xdd, 0xe1, 0xa9, 0x8d, 0xf1, 0x04, 0x1b,
	0x0d, 0x26, 0xe0, 0x3a, 0x23, 0x7b, 0x32, 0x77, 0x8d, 0x26, 0xda, 0x05, 0xbd, 0xdf, 0x1d, 0xf7,
	0xed, 0xe1, 0xd0, 0x1e, 0x18, 0x2d, 0xc6, 0xb3, 0x3f, 0x9b, 0x3a, 0xd8, 0x1e, 0x18, 0xba, 0x39,
	0x00, 0xe8, 0xc7, 0x51, 0x1a, 0x87, 0x64, 0x18, 0x9f, 0xb3, 0x90, 0x0b, 0x58, 0xc4, 0x46, 0x3e,
	0x51, 0x3c, 0xa1, 0x84, 0xb1, 0xc4, 0xbc, 0xf0, 0xa8, 0xc7, 0xaf, 0x6d, 0x07, 0xf3, 0xb5, 0xf9,
	0x0f, 0x0d, 0xda, 0xbc, 0x54, 0xfd, 0x0f, 0xee, 0x74, 0x87, 0x95, 0x18, 0xee, 0x13, 0xc5, 0x9c,
	0xb4, 0x06, 0xd6, 0xb6, 0x6d, 0xe6, 0xb6, 0x5d, 0xbf, 0xae, 0x1c, 0x44, 0xa3, 0xa7, 0x5d, 0xf2,
	0x91, 0xdd, 0x1d, 0xba, 0x47, 0xac, 0x33, 0xdc, 0x05, 0x7d, 0x3e, 0xce, 0xc9, 0x0a, 0x23, 0x65,
	0x6b, 0x68, 0xcb, 0xe6, 0x70, 0x36, 0xb4, 0xed, 0x29, 0x0f, 0x26, 0xb3, 0x0f, 0xbb, 0xca, 0xab,
	0x48, 0x8a, 0x0e, 0x61, 0xf7, 0x4c, 0x05, 0xe4, 0x7c, 0xb8, 0xa3, 0x9e, 0x08, 0x97, 0x45, 0xcc,
	0xbf, 0x56, 0x60, 0x87, 0xb3, 0x47, 0x84, 0x26, 0x81, 0xff, 0xdf, 0x5d, 0xd0, 0x7d, 0xd0, 0x73,
	0x43, 0xe4, 0x01, 0x77, 0xc7, 0x52, 0x77, 0xb5, 0x9c, 0x9c, 0x2d, 0x1b, 0xaa, 0x42, 0x1c, 0x7d,
	0x00, 0xad, 0x94, 0xc6, 0x89, 0x77, 0x5e, 0x0c, 0x92, 0xaf, 0x94, 0x55, 0x67, 0x92, 0x2b, 0x23,
	0x35, 0x17, 0xee, 0x0c, 0x61, 0xaf, 0xbc, 0xeb, 0x96, 0x50, 0x7d, 0xb3, 0x1c, 0xaa, 0x7b, 0x62,
	0xe7, 0x5c, 0x4d, 0x89, 0xd8, 0xce, 0x43, 0xd8, 0x2d, 0xbd, 0x68, 0xcb, 0x66, 0x6f, 0x94, 0x37,
	0xdb, 0xcd, 0xaf, 0x95, 0x6b, 0xa9, 0xd1, 0xff, 0xb7, 0x8a, 0xb4, 0x4c, 0xfe, 0xa2, 0x62, 0xf2,
	0xd6, 0x94, 0xc9, 0xbb, 0xe4, 0x55, 0x95, 0xeb, 0x5e, 0xc5, 0x8a, 0xd0, 0x2a, 0xc3, 0xe4, 0xa7,
	0x19, 0x49, 0x69, 0xca, 0xbd, 0xae, 0x8a, 0x55, 0x08, 0x75, 0xa0, 0xe5, 0xaf, 0xb2, 0x79, 0xca,
	0xba, 0xfc, 0x1a, 0x67, 0x17, 0x34, 0xd3, 0x5e, 0x92, 0x65, 0xa1, 0x5d, 0x17, 0xda, 0x0a, 0xc4,
	0xb4, 0x97, 0x64, 0x29, 0xb4, 0x1b, 0x42, 0x3b, 0xa7, 0x19, 0x2f, 0x21, 0x3c, 0xb1, 0xa4, 0xdc,
	0xa9, 0xeb, 0xb8, 0xa0, 0xd1, 0xdb, 0xb9, 0xb7, 0x8b, 0x99, 0xe8, 0x76, 0xf9, 0x46, 0xcb, 0xfe,
	0x7e, 0xfc, 0x34, 0x7f, 0xcf, 0xab, 0x03, 0xf7, 0xf7, 0xfe, 0x64, 0x34, 0x1d, 0xda, 0x2e, 0xcf,
	0x2b, 0x3a, 0xd4, 0x45, 0x9e, 0xa8, 0xb2, 0x26, 0x77, 0x32, 0x19, 0x9d, 0x1e, 0x3b, 0x3c, 0x37,
	0xd4, 0xcc, 0x3f, 0x68, 0xd2, 0x51, 0xe5, 0x85, 0x6f, 0xbd, 0xd3, 0x03, 0xb8, 0xe1, 0x7b, 0x2b,
	0xcf, 0x0f, 0xe8, 0x95, 0x13, 0xf5, 0xae, 0x28, 0x49, 0xf9, 0xcd, 0x56, 0xf1, 0x75, 0x98, 0xe5,
	0x93, 0x8c, 0x7d, 0xac, 0x5a, 0x6d, 0x75, 0x5c, 0xc2, 0x98, 0x85, 0x96, 0x71, 0x16, 0xd1, 0xa9,
	0x47, 0x2f, 0x64, 0xf3, 0xb0, 0x06, 0x58, 0x01, 0xce, 0xbd, 0xd8, 0xc9, 0xc7, 0x20, 0x05, 0x31,
	0x7f, 0xa3, 0x49, 0x2f, 0x48, 0xf3, 0xd0, 0x3a, 0x84, 0x06, 0x8f, 0xa4, 0x3c, 0x30, 0x3b, 0x56,
	0x89, 0x2f, 0x29, 0xe1, 0xe7, 0x52, 0xb2, 0x73, 0x24, 0xd3, 0xd7, 0x0b, 0x7a, 0xa5, 0xdc, 0x52,
	0xf5, 0xca, 0xbf, 0x6b, 0xca, 0x3c, 0xa1, 0x8e, 0x88, 0xda, 0xf3, 0x8d, 0x88, 0xdb, 0x67, 0xcd,
	0x8f, 0x61, 0xe7, 0x89, 0x98, 0x0c, 0x53, 0x97, 0xcd, 0xc1, 0x55, 0x19, 0xc2, 0xf9, 0x06, 0xd6,
	0x89, 0xc2, 0x15, 0x9f, 0x56, 0x52, 0xe8, 0x7c, 0x0c, 0x37, 0x37, 0x44, 0x5e, 0xa8, 0xeb, 0x3c,
	0x86, 0xdd, 0x11, 0x6f, 0x7b, 0x58, 0x77, 0x1d, 0x47, 0xdc, 0xb4, 0x0b, 0xf2, 0xd8, 0xcb, 0x42,
	0x7a, 0xc2, 0x35, 0x44, 0x6f, 0x54, 0xc2, 0x58, 0xeb, 0xc8, 0x77, 0x60, 0xfe, 0x51, 0x3d, 0xa8,
	0x63, 0x49, 0x99, 0x47, 0x00, 0xfd, 0xe9, 0xfc, 0xeb, 0x76, 0xaa, 0x7c, 0xed, 0x4e, 0x95, 0x62,
	0xa7, 0x21, 0xec, 0xb9, 0xa2, 0x1f, 0xfc, 0x7f, 0x9c, 0xeb, 0x17, 0x1a, 0x20, 0xa5, 0x9d, 0xcc,
	0xb7, 0x3c, 0x80, 0x1b, 0x52, 0x7d, 0x14, 0x44, 0xea, 0xae, 0xd7, 0x61, 0x55, 0xd2, 0xfb, 0xf2,
	0xa4, 0xb8, 0x49, 0x45, 0x52, 0xc2, 0xca, 0x11, 0xaa, 0xa5, 0x23, 0xfc, 0xab, 0x02, 0xe8, 0x38,
	0x88, 0x68, 0x2c, 0x5c, 0x24, 0x4b, 0x78, 0xeb, 0x8c, 0xbe, 0x0d, 0x7a, 0xee, 0x22, 0xb9, 0x5f,
	0xeb, 0x6b, 0xf7, 0x59, 0xf3, 0xd0, 0xfb, 0xb0, 0xbb, 0x54, 0xed, 0x54, 0xe4, 0xe4, 0x92, 0xf5,
	0x70, 0x59, 0x88, 0xcd, 0xdb, 0xfe, 0x2a, 0xcb, 0x55, 0xaa, 0x72, 0xde, 0x5e, 0xdb, 0x08, 0x2b,
	0x6c, 0xf4, 0x01, 0xec, 0xd1, 0xd2, 0x9d, 0xcb, 0xff, 0x4d, 0x37, 0xac, 0xb2, 0x29, 0xf0, 0x35,
	0x31, 0xd4, 0x07, 0xe4, 0x6d, 0xdc, 0xae, 0x9c, 0x26, 0x6f, 0x59, 0x9b, 0x17, 0x8f, 0xb7, 0x88,
	0xa3, 0x1f, 0xc2, 0xcd, 0x2f, 0xe2, 0xb3, 0xf2, 0x9b, 0xe4, 0x5f, 0xaa, 0x8d, 0x03, 0x6c, 0x4a,
	0x9a, 0x1d, 0xa8, 0x0d, 0xe3, 0xf3, 0xb4, 0xe8, 0x62, 0x34, 0xa5, 0x8b, 0xf9, 0x65, 0x05, 0x6e,
	0x74, 0xd7, 0x93, 0xcf, 0xc0, 0xa3, 0x1e, 0xfa, 0x00, 0x76, 0xfd, 0x30, 0x4b, 0x29, 0x49, 0x04,
	0x87, 0x2b, 0xb4, 0x0f, 0x6f, 0x5a, 0x82, 0x9c, 0x92, 0x64, 0x19, 0xa4, 0x2c, 0xae, 0x70, 0x59,
	0x0e, 0x7d, 0x0c, 0x37, 0xc9, 0xfa, 0x3f, 0xb3, 0x54, 0xae, 0x3c, 0x4d, 0x79, 0x53, 0x16, 0xdd,
	0x67, 0xb5, 0x83, 0x7a, 0xfc, 0x94, 0x22, 0xde, 0x5f, 0xb3, 0xae, 0x9d, 0xce, 0x1a, 0x49, 0x01,
	0x59, 0xb5, 0x73, 0xf9, 0xce, 0xf7, 0x59, 0xb4, 0x2a, 0xac, 0x17, 0x0a, 0xf5, 0x3f, 0x69, 0x60,
	0x5c, 0x3f, 0x20, 0xff, 0xd9, 0x24, 0xa7, 0x22, 0x27, 0xff, 0x37, 0xa6, 0x20, 0xe8, 0x6d, 0xa8,
	0x25, 0x71, 0x98, 0x8f, 0x37, 0x2f, 0x6d, 0x7c, 0xa1, 0x85, 0xe3, 0x90, 0x60, 0x2e, 0x63, 0xfe,
	0x04, 0x6a, 0x8c, 0xda, 0xf8, 0x73, 0x37, 0x9d, 0xf7, 0x86, 0x4e, 0xdf, 0xd0, 0xd8, 0xcc, 0xd2,
	0x9d, 0xbb, 0x47, 0xf6, 0xd8, 0x75, 0xfa, 0x5d, 0x51, 0xb3, 0x00, 0x1a, 0x6c, 0x88, 0xb1, 0xb1,
	0xf8, 0xe3, 0x62, 0x0f, 0x1c, 0x77, 0x82, 0x8d, 0x1a, 0xab, 0x65, 0xdd, 0xc1, 0xc8, 0x19, 0x1b,
	0x75, 0xb6, 0x9c, 0x3c, 0x1a, 0xdb, 0xd8, 0x68, 0x98, 0xbf, 0xd7, 0xe0, 0x66, 0x5f, 0x98, 0x63,
	0x46, 0xfc, 0x84, 0x50, 0x6e, 0xcb, 0x3b, 0xa0, 0x4b, 0xb0, 0xf8, 0x84, 0x35, 0xc0, 0xa6, 0x78,
	0x49, 0xf4, 0xc3, 0x80, 0x44, 0x54, 0x28, 0xca, 0xeb, 0xd9, 0xc6, 0x42, 0x3f, 0x82, 0x57, 0xfa,
	0xaa, 0xcd, 0xb9, 0x5d, 0x04, 0xef, 0x98, 0x5c, 0xf1, 0x30, 0xda, 0xc1, 0x5f, 0x27, 0x62, 0x7e,
	0x55, 0x01, 0x9d, 0x0d, 0xc4, 0xa2, 0x6b, 0x7e, 0x9e, 0xee, 0xfb, 0xad, 0xf2, 0x1c, 0x69, 0x58,
	0x85, 0x7a, 0x79, 0xc2, 0x79, 0x0b, 0xf6, 0x8a, 0xa1, 0x85, 0x4f, 0x22, 0xb2, 0xb9, 0xb9, 0x86,
	0xb2, 0x77, 0x92, 0x68, 0xb1, 0x96, 0x12, 0x3d, 0x4e, 0x09, 0x7b, 0xca, 0x58, 0xaa, 0x8c, 0x9c,
	0x9a, 0xda, 0x6e, 0x54, 0xca, 0xed, 0x06, 0x9f, 0x5c, 0x06, 0xb6, 0x20, 0x6a, 0xeb, 0xde, 0xa3,
	0x7e, 0xad, 0xf7, 0x68, 0x98, 0xc7, 0x70, 0xcb, 0x25, 0x21, 0x59, 0xc5, 0x09, 0x9d, 0x91, 0xe4,
	0x49, 0xe0, 0x13, 0x6e, 0xb5, 0xfc, 0x47, 0x90, 0xa6, 0xfc, 0x08, 0xe2, 0x3f, 0x0f, 0xc8, 0x82,
	0x44, 0x34, 0xf0, 0xc2, 0x34, 0xff, 0x6b, 0xa1, 0x40, 0x3d, 0xeb, 0xc7, 0xdf, 0x11, 0x7f, 0x20,
	0x2c, 0x3f, 0x5e, 0xde, 0xbb, 0x64, 0x19, 0xf5, 0x22, 0x3b, 0x13, 0x8b, 0xef, 0xfa, 0x61, 0x70,
	0x2f, 0x88, 0x28, 0x49, 0x22, 0x2f, 0xbc, 0x47, 0xaf, 0x56, 0x24, 0x3d, 0x6b, 0xf0, 0xd9, 0xed,
	0x7b, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x18, 0xa2, 0xa9, 0x39, 0x52, 0x1a, 0x00, 0x00,
}
